(function(){
const CONFIG=window.GOLD71_CONFIG||{};
const OWNER_PASSWORD=CONFIG.ownerPassword||'7171';
const APP=CONFIG.app||{};
const raw = window.GOLD71_MENU_RAW || [];
const PRODUCTS=raw.map(([id,name,category,localPrice,appPrice,appAvailable])=>({id,name,category,localPrice,appPrice,appAvailable:!!appAvailable}));
const $=id=>document.getElementById(id);const money=n=>'$'+Number(n||0).toFixed(0);const labels=Object.fromEntries(APP.origins||[]);const isError=o=>o&&o.status==='Error de pedido';const validOrders=orders=>(orders||[]).filter(o=>!isError(o));const fav=CONFIG.favorites||[];
let state={origin:'mesa',mesa:1,employee:null,account:1,category:'Favoritos',cart:[],orders:JSON.parse(localStorage.getItem('g71_orders')||'[]'),archives:JSON.parse(localStorage.getItem('g71_archives')||'[]'),seq:Number(localStorage.getItem('g71_seq')||1),target:null,editId:null,returnScreen:'screenActive',editArchiveId:null};
function save(){localStorage.setItem('g71_orders',JSON.stringify(state.orders));localStorage.setItem('g71_seq',state.seq);localStorage.setItem('g71_archives',JSON.stringify(state.archives||[]))}
function recalcCurrentTakeoutTotals(){let changed=false;state.orders.forEach(o=>{if(o.origin==='llevar'){const t=(o.items||[]).reduce((a,i)=>a+itemTotal(i),0)+packagingTotal(o.items||[]);if(o.total!==t){o.total=t;changed=true}}});if(changed)save()}
function isDiscountExcluded(p){return ['hamb-monster-doble','hamb-monster-triple','malteada-monster','refresco','coca-zero','fuze-tea','agua-bonafont'].includes(p.id)}function price(p){const base=state.origin==='personal'?p.localPrice:((state.origin==='didi'||state.origin==='uber')?p.appPrice:p.localPrice);return state.origin==='personal'&&!isDiscountExcluded(p)?Math.floor(base*0.5):base}function avail(p){return (state.origin==='didi'||state.origin==='uber')?p.appAvailable:p.localPrice!==null}
function init(){recalcCurrentTakeoutTotals();renderTabs();renderOrigin();renderTables();renderEmployees();renderCats();renderQuick();renderProducts();renderAccounts();renderCart();renderOrders();renderSummary();renderArchives();$('next').textContent='#'+String(state.seq).padStart(3,'0')}
function flash(el){if(!el)return;el.classList.remove('tapFlash');void el.offsetWidth;el.classList.add('tapFlash')}
function renderTabs(){[['tabNew','screenNew'],['tabActive','screenActive'],['tabClose','screenClose']].forEach(([b,s])=>$(b).onclick=()=>show(s,b));$('backClose').onclick=()=>show('screenClose','tabClose');$('archivesBtn').onclick=()=>{if(ownerPass())show('screenArchives','tabClose')}}function show(screen,btn){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('on'));$(screen).classList.add('on');document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('on'));$(btn).classList.add('on');renderOrders();renderSummary()}
function renderOrigin(){$('origin').innerHTML=APP.origins.map(([id,l])=>`<button class="${state.origin===id?'on':''}" data-origin="${id}">${l}</button>`).join('');document.querySelectorAll('[data-origin]').forEach(b=>b.onclick=()=>{flash(b);state.origin=b.dataset.origin;state.mesa=state.origin==='mesa'?(state.mesa||1):null;state.employee=state.origin==='personal'?(state.employee||APP.employees[0]):null;state.category='Favoritos';$('search').value='';renderOrigin();renderTables();renderEmployees();renderCats();renderProducts();renderAccounts();renderCart()})}
function renderTables(){$('tables').innerHTML=state.origin==='mesa'?Array.from({length:12},(_,i)=>`<button class="${state.mesa===i+1?'on':''}" data-mesa="${i+1}">Mesa ${i+1}</button>`).join(''):'';document.querySelectorAll('[data-mesa]').forEach(b=>b.onclick=()=>{flash(b);state.mesa=Number(b.dataset.mesa);renderTables();renderCart()})}function renderEmployees(){$('employees').innerHTML=state.origin==='personal'?'<p class="mut" style="width:100%;margin:4px 0 0">Empleado:</p>'+APP.employees.map(n=>`<button class="${state.employee===n?'on':''}" data-emp="${n}">${n}</button>`).join(''):'';document.querySelectorAll('[data-emp]').forEach(b=>b.onclick=()=>{flash(b);state.employee=b.dataset.emp;renderEmployees();renderCart()})}
function renderAccounts(){$('accounts').innerHTML=Array.from({length:6},(_,i)=>`<button class="${state.account===i+1?'on':''}" data-acc="${i+1}">Cuenta ${i+1}</button>`).join('');document.querySelectorAll('[data-acc]').forEach(b=>b.onclick=()=>{flash(b);state.account=Number(b.dataset.acc);renderAccounts();renderCart()})}
const CATEGORY_ORDER=CONFIG.categoryOrder||[];
const CATEGORY_LABELS=CONFIG.categoryLabels||{};
function catLabel(c){return CATEGORY_LABELS[c]||c}
function categories(){const available=[...new Set(PRODUCTS.filter(avail).map(p=>p.category))];return ['Favoritos',...CATEGORY_ORDER.filter(c=>available.includes(c)),...available.filter(c=>!CATEGORY_ORDER.includes(c)).sort()]}function renderCats(){$('cats').innerHTML=categories().map(c=>`<button class="${state.category===c?'on':''}" data-cat="${c}">${catLabel(c)}</button>`).join('');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{flash(b);state.category=b.dataset.cat;$('search').value='';renderCats();renderProducts()})}
function renderProducts(){const q=$('search').value.trim().toLowerCase();let list=PRODUCTS.filter(avail);if(q){list=list.filter(p=>p.name.toLowerCase().includes(q)||p.category.toLowerCase().includes(q))}else if(state.category==='Favoritos'){list=list.filter(p=>fav.includes(p.id))}else{list=list.filter(p=>p.category===state.category)}list=list.slice().sort((a,b)=>a.name.localeCompare(b.name,'es',{sensitivity:'base'}));$('products').innerHTML=list.length?list.map(p=>`<button class="prod" data-prod="${p.id}">${p.name}<small>${catLabel(p.category)} · ${money(price(p))}</small></button>`).join(''):'<div class="empty">No hay productos con ese filtro.</div>';document.querySelectorAll('[data-prod]').forEach(b=>b.onclick=()=>{flash(b);openExtras(b.dataset.prod)})}
$('search').addEventListener('input',renderProducts);
function renderQuick(){$('quick').innerHTML=APP.quick.map(n=>`<button data-note="${n}">${n}</button>`).join('');document.querySelectorAll('[data-note]').forEach(b=>b.onclick=()=>{flash(b);$('notes').value=($('notes').value?$('notes').value+'; ':'')+b.dataset.note})}
function extrasFor(p){const c=p.category.toLowerCase();if(c.includes('caf')||c.includes('bebidas')||c.includes('tés'))return [];if(c.includes('hamburguesas'))return APP.extras.hamburguesa;if(c.includes('ensaladas'))return APP.extras.ensalada;if(c.includes('huevos'))return APP.extras.desayuno;if(c.includes('waffles salados'))return APP.extras.waffle;if(c.includes('croissants')||c.includes('sándwiches')||c.includes('sandwiches')||c.includes('paninis'))return APP.extras.comida;return []}
function openExtras(id){state.target=PRODUCTS.find(p=>p.id===id);const list=extrasFor(state.target);if(!list.length){addProduct(state.target,[]);return}$('extraTitle').textContent=state.target.name;$('extras').innerHTML=list.map(([n,p],i)=>`<label class="extra"><input type="checkbox" data-extra="${i}"><span>${n} +${money(p)}</span></label>`).join('');$('extraModal').dataset.kind=state.target.id;document.querySelectorAll('.extra').forEach(l=>l.onclick=()=>flash(l));$('extraModal').classList.add('on')}
$('extraCancel').onclick=()=>$('extraModal').classList.remove('on');$('extraAdd').onclick=()=>{const list=extrasFor(state.target);const extras=[...document.querySelectorAll('[data-extra]:checked')].map(x=>{const e=list[Number(x.dataset.extra)];return{name:e[0],price:e[1]}});addProduct(state.target,extras);$('extraModal').classList.remove('on')};
function addProduct(p,extras){const acc=state.account||1;const key=p.id+'|'+acc+'|'+extras.map(e=>e.name).join(',');const found=state.cart.find(i=>i.key===key);if(found)found.qty++;else state.cart.push({key,id:p.id,name:p.name,base:price(p),qty:1,extras,account:acc});renderCart()}
function currentLabel(){return state.origin==='mesa'?`🪑 Mesa ${state.mesa}`:(state.origin==='personal'?`👤 Personal · ${state.employee||'Sin nombre'}`:labels[state.origin])}function itemTotal(i){return (i.base+i.extras.reduce((a,e)=>a+e.price,0))*i.qty}function total(){let t=state.cart.reduce((a,i)=>a+itemTotal(i),0);if(state.origin==='llevar'&&state.cart.length)t+=packagingTotal(state.cart);return t}
function itemsByAccount(items){const g={};items.forEach(i=>{const a=i.account||1;(g[a]||(g[a]=[])).push(i)});return g}
function accountSubtotal(items,acc){return items.filter(i=>(i.account||1)===Number(acc)).reduce((a,i)=>a+itemTotal(i),0)}
function needsPackaging(item){return !APP.noPackaging.includes(item.id)}
function packagingQty(items){return (items||[]).filter(needsPackaging).reduce((a,i)=>a+(Number(i.qty)||0),0)}
function packagingTotal(items){return packagingQty(items)*APP.packagingFee}
function groupedList(items){const g=itemsByAccount(items);return Object.keys(g).sort((a,b)=>a-b).map(acc=>`<div class="accountBlock"><h4>Cuenta ${acc} · ${money(accountSubtotal(items,acc))}</h4><ul>${g[acc].map(i=>`<li>${i.qty} × ${i.name}${i.extras.length?' ('+i.extras.map(e=>e.name).join(', ')+')':''}</li>`).join('')}</ul></div>`).join('')}
function renderCart(){
  $('meta').textContent=currentLabel();
  renderAccounts();
  if(!state.cart.length){
    $('cart').innerHTML='<div class="empty">Agrega productos al pedido.</div>';
  }else{
    const g=itemsByAccount(state.cart);
    $('cart').innerHTML=Object.keys(g).sort((a,b)=>a-b).map(acc=>`<div class="accountBlock"><h4>Cuenta ${acc} · ${money(accountSubtotal(state.cart,acc))}</h4>${g[acc].map(i=>{const idx=state.cart.indexOf(i);return `<div class="item"><b>${i.qty} × ${i.name}</b><small>${i.extras.length?i.extras.map(e=>e.name).join(', ')+' · ':''}${money(itemTotal(i))}</small><div class="ctrl"><button data-plus="${idx}">+</button><button data-minus="${idx}">−</button><button data-del="${idx}">Eliminar</button><button data-move="${idx}">Cambiar cuenta</button></div></div>`}).join('')}</div>`).join('')+(state.origin==='llevar'?`<div class="item"><b>Envase x${packagingQty(state.cart)}</b><small>${money(packagingTotal(state.cart))}</small></div>`:'');
  }
  document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>{flash(b);state.cart[Number(b.dataset.plus)].qty++;renderCart()});
  document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>{flash(b);const i=Number(b.dataset.minus);state.cart[i].qty--;if(state.cart[i].qty<1)state.cart.splice(i,1);renderCart()});
  document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{flash(b);state.cart.splice(Number(b.dataset.del),1);renderCart()});
  document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{flash(b);const i=Number(b.dataset.move);const n=Number(prompt('Mover a cuenta (1-6):',state.cart[i].account||1));if(n>=1&&n<=6){state.cart[i].account=n;state.cart[i].key=state.cart[i].id+'|'+n+'|'+state.cart[i].extras.map(e=>e.name).join(',');renderCart()}});
  $('total').textContent=money(total())
}
$('clear').onclick=()=>{flash($('clear'));state.cart=[];state.editId=null;state.editArchiveId=null;state.account=1;$('notes').value='';renderAccounts();renderCart();$('send').textContent='Enviar pedido'};$('send').onclick=()=>{flash($('send'));if(!state.cart.length){alert('Agrega al menos un producto.');return}if(state.origin==='personal'&&!state.employee){alert('Selecciona quién del personal está pidiendo.');return}const payload={origin:state.origin,mesa:state.mesa,employee:state.employee,items:JSON.parse(JSON.stringify(state.cart)),notes:$('notes').value,total:total()};if(state.editArchiveId&&state.editId){const a=(state.archives||[]).find(x=>x.id===state.editArchiveId);const o=a&&(a.orders||[]).find(x=>x.id===state.editId);if(o){Object.assign(o,payload);o.adminEdited=true;o.adminEditedAt=Date.now();o.adminEditNote='Editado por administrador después del cierre';a.inventory=buildInventorySnapshot(a.orders||[]);a.summary=buildSummary(a.orders||[],'Corte guardado',null);a.updatedAt=new Date().toISOString();}const archiveId=state.editArchiveId;state.editId=null;state.editArchiveId=null;$('send').textContent='Enviar pedido';state.cart=[];state.account=1;$('notes').value='';save();init();show('screenArchives','tabClose');renderArchiveDetail(archiveId);return}else if(state.editId){const o=state.orders.find(x=>x.id===state.editId);Object.assign(o,payload);state.editId=null;$('send').textContent='Enviar pedido';}else{state.orders.unshift({id:state.seq++,created:Date.now(),status:'Pendiente',...payload});}state.cart=[];state.account=1;$('notes').value='';save();init();show('screenActive','tabActive')};
function orderPlace(o){return o.origin==='mesa'?'🪑 Mesa '+o.mesa:(o.origin==='personal'?'👤 Personal · '+(o.employee||'Sin nombre'):labels[o.origin])}function minutes(t){return Math.max(0,Math.floor((Date.now()-t)/60000))}function renderOrders(){const active=state.orders.filter(o=>o.status!=='Entregado'&&!isError(o));$('orders').innerHTML=active.length?active.map(o=>`<div class="order"><h3>#${String(o.id).padStart(3,'0')} · ${orderPlace(o)}</h3><span class="pill">${o.status}</span> <span class="pill">${minutes(o.created)} min</span> <span class="pill">${money(o.total)}</span>${groupedList(o.items)}${o.origin==='llevar'?`<ul><li>Envase x${packagingQty(o.items)} (${money(packagingTotal(o.items))})</li></ul>`:''}${o.notes?`<p>${o.notes}</p>`:''}<button data-edit="${o.id}">Editar</button><button class="danger" data-error="${o.id}">Marcar error</button><button class="next" data-next="${o.id}">${o.status} →</button></div>`).join(''):'<div class="empty">Sin pedidos activos.</div>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editOrder(Number(b.dataset.edit)));document.querySelectorAll('[data-error]').forEach(b=>b.onclick=()=>markOrderError(Number(b.dataset.error)));document.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>{const o=state.orders.find(x=>x.id===Number(b.dataset.next));o.status={Pendiente:'Preparando',Preparando:'Listo',Listo:'Entregado'}[o.status]||'Entregado';save();renderOrders();renderSummary()})}
function buildSummary(orders,title,seqText){const valid=validOrders(orders);const errors=(orders||[]).filter(isError);const groups={mesa:[],llevar:[],didi:[],uber:[],personal:[]};valid.forEach(o=>(groups[o.origin]||(groups[o.origin]=[])).push(o));let grand=0,txt=`Gold 71 Café · Galaxia OS\n${title}\n\n`;APP.origins.forEach(([id,l])=>{const sum=(groups[id]||[]).reduce((a,o)=>a+o.total,0);grand+=sum;txt+=`${l}: ${(groups[id]||[]).length} pedidos · ${money(sum)}\n`});txt+=`\nTOTAL VENTAS: ${money(grand)}\nErrores de pedido: ${errors.length}`;if(errors.length){const lost=errors.reduce((a,o)=>a+(o.total||0),0);txt+=` · Monto no cobrado: ${money(lost)}`}if(seqText)txt+=`\n${seqText}`;return txt}
function productCounts(orders){const counts={};validOrders(orders).forEach(o=>o.items.forEach(i=>{const name=i.name+(i.extras&&i.extras.length?' ('+i.extras.map(e=>e.name).join(', ')+')':'');counts[name]=(counts[name]||0)+i.qty}));return Object.entries(counts).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))}
function renderProductCounts(orders){const counts=productCounts(orders);return counts.length?`<div class="accountBlock"><h4>Productos vendidos</h4><ul>${counts.map(([n,q])=>`<li>${q} × ${n}</li>`).join('')}</ul></div>`:''}

function renderErrors(orders){const errors=(orders||[]).filter(isError);return errors.length?`<div class="accountBlock errorBlock"><h4>⚠ Errores de pedido (${errors.length})</h4>${errors.map(o=>`<div class="errorRow"><b>#${String(o.id).padStart(3,'0')} · ${orderPlace(o)} · ${money(o.total)}</b><br><small>${o.errorReason||'Sin motivo'} · ${o.errorEmployee||'Sin responsable'} · ${new Date(o.errorAt||o.created).toLocaleString()}</small>${groupedList(o.items)}</div>`).join('')}</div>`:''}
function ensureErrorModal(){let m=$('errorModal');if(m)return m;m=document.createElement('div');m.id='errorModal';m.className='modalBack';m.innerHTML=`<div class="modal"><h2>⚠ Marcar error de pedido</h2><p class="mut" id="errorModalOrder"></p><h3>¿Quién cometió o registró el error?</h3><div id="errorEmployeeChoices" class="choiceGrid"></div><h3>Motivo</h3><div id="errorReasonChoices" class="choiceGrid"></div><p class="mut">El pedido no se borrará. Quedará guardado como error y no sumará en ventas ni productos vendidos.</p><div class="row"><button id="errorCancel">Cancelar</button><button id="errorConfirm" class="danger">Marcar como error</button></div></div>`;document.body.appendChild(m);return m}
function markOrderError(id){const o=state.orders.find(x=>x.id===id);if(!o)return;const m=ensureErrorModal();const reasons=['Cliente canceló','Se tomó mal la orden','Producto equivocado','Pedido duplicado','Error de captura','Error de cocina','Otro'];let employee='';let reason='';$('errorModalOrder').textContent=`Pedido #${String(o.id).padStart(3,'0')} · ${orderPlace(o)} · ${money(o.total)}`;$('errorEmployeeChoices').innerHTML=APP.employees.map(n=>`<button data-error-emp="${n}">${n}</button>`).join('');$('errorReasonChoices').innerHTML=reasons.map(n=>`<button data-error-reason="${n}">${n}</button>`).join('');const update=()=>{$('errorConfirm').disabled=!(employee&&reason);document.querySelectorAll('[data-error-emp]').forEach(b=>b.classList.toggle('on',b.dataset.errorEmp===employee));document.querySelectorAll('[data-error-reason]').forEach(b=>b.classList.toggle('on',b.dataset.errorReason===reason))};document.querySelectorAll('[data-error-emp]').forEach(b=>b.onclick=()=>{flash(b);employee=b.dataset.errorEmp;update()});document.querySelectorAll('[data-error-reason]').forEach(b=>b.onclick=()=>{flash(b);reason=b.dataset.errorReason;update()});$('errorCancel').onclick=()=>m.classList.remove('on');$('errorConfirm').onclick=()=>{if(!(employee&&reason))return;o.status='Error de pedido';o.errorReason=reason;o.errorEmployee=employee;o.errorAt=Date.now();save();m.classList.remove('on');renderOrders();renderSummary();renderArchives()};update();m.classList.add('on')}


function renderSummary(){$('summary').textContent=buildSummary(state.orders,'Corte del día',`Siguiente pedido: #${String(state.seq).padStart(3,'0')}`);$('history').innerHTML=renderProductCounts(state.orders)+renderErrors(state.orders)+state.orders.map(o=>`<div class="historyItem ${isError(o)?'orderError':''}"><b>#${String(o.id).padStart(3,'0')} · ${orderPlace(o)} · ${money(o.total)}</b><br><small>${new Date(o.created).toLocaleTimeString()} · ${o.status}${isError(o)?' · '+(o.errorReason||'Sin motivo')+' · '+(o.errorEmployee||'Sin responsable'):''}</small>${groupedList(o.items)}${o.origin==='llevar'?`<ul><li>Envase x${packagingQty(o.items)} (${money(packagingTotal(o.items))})</li></ul>`:''}${o.notes?`<p>${o.notes}</p>`:''}${!isError(o)?`<button data-edit="${o.id}">Editar</button><button class="danger" data-error="${o.id}">Marcar error</button>`:''}</div>`).join('');document.querySelectorAll('#history [data-edit]').forEach(b=>b.onclick=()=>editOrder(Number(b.dataset.edit)));document.querySelectorAll('#history [data-error]').forEach(b=>b.onclick=()=>markOrderError(Number(b.dataset.error)))}

function editOrder(id,archiveId){let o=null;if(archiveId){const a=(state.archives||[]).find(x=>x.id===archiveId);o=a&&(a.orders||[]).find(x=>x.id===id);state.editArchiveId=archiveId}else{o=state.orders.find(x=>x.id===id);state.editArchiveId=null}if(!o)return;if(isError(o)){alert('Este pedido está marcado como error y no se puede editar.');return;}state.editId=id;state.origin=o.origin;state.mesa=o.mesa||null;state.employee=o.employee||null;state.cart=JSON.parse(JSON.stringify(o.items)).map(i=>({...i,account:i.account||1,key:i.key||i.id+'|'+(i.account||1)+'|'+(i.extras||[]).map(e=>e.name).join(',')}));state.account=1;$('notes').value=o.notes||'';state.category='Favoritos';$('search').value='';$('send').textContent=archiveId?'Guardar corrección':'Guardar cambios';renderOrigin();renderTables();renderEmployees();renderCats();renderProducts();renderCart();show('screenNew','tabNew')}
function ownerPass(){const p=prompt('Contraseña de administración:');return p===OWNER_PASSWORD}
function closeDay(){if(!state.orders.length){alert('No hay pedidos para cerrar.');return}if(!confirm('Se guardará el corte de hoy en Historial de cierres y se limpiará la pantalla para empezar de nuevo en #001. ¿Cerrar día?'))return;const now=new Date();const archive={id:Date.now(),closedAt:now.toISOString(),label:now.toLocaleDateString(),orders:JSON.parse(JSON.stringify(state.orders)),summary:buildSummary(state.orders,'Corte guardado',null)};state.archives.unshift(archive);state.orders=[];state.seq=1;save();renderOrders();renderSummary();renderArchives();$('next').textContent='#001';alert('Corte guardado. Ya puedes iniciar el nuevo día desde #001.')}
function renderArchives(){if(!$('archives'))return;const list=state.archives||[];$('archives').innerHTML=list.length?list.map(a=>`<div class="historyItem"><div class="row between"><div><b>${new Date(a.closedAt).toLocaleDateString()} · ${a.orders.length} pedidos</b><br><small>Cerrado: ${new Date(a.closedAt).toLocaleString()}</small></div><button class="danger" data-del-archive="${a.id}">Borrar respaldo</button></div><pre>${buildSummary(a.orders,'Corte guardado',null)}</pre>${renderProductCounts(a.orders)}${renderErrors(a.orders)}${a.orders.map(o=>`<div class="accountBlock ${isError(o)?'orderError':''}"><h4>#${String(o.id).padStart(3,'0')} · ${orderPlace(o)} · ${money(o.total)}</h4><small>${new Date(o.created).toLocaleTimeString()} · ${o.status}${isError(o)?' · '+(o.errorReason||'Sin motivo')+' · '+(o.errorEmployee||'Sin responsable'):''}</small>${groupedList(o.items)}${o.origin==='llevar'?`<ul><li>Envase x${packagingQty(o.items)} (${money(packagingTotal(o.items))})</li></ul>`:''}${o.notes?`<p>${o.notes}</p>`:''}</div>`).join('')}</div>`).join(''):'<div class="empty">No hay cortes guardados.</div>';document.querySelectorAll('[data-del-archive]').forEach(b=>b.onclick=()=>deleteArchive(Number(b.dataset.delArchive)))}
function deleteArchive(id){if(!ownerPass())return;if(!confirm('Esto sí borra definitivamente este respaldo. ¿Seguro?'))return;state.archives=(state.archives||[]).filter(a=>a.id!==id);save();renderArchives()}

// === v3.1 Administración, historial segmentado e inventario ===
const INV_ITEMS=(window.GOLD71_INVENTORY&&window.GOLD71_INVENTORY.items)||[];
function getInventory(){const raw=JSON.parse(localStorage.getItem('g71_inventory')||'{}');INV_ITEMS.forEach(([id])=>{if(!raw[id])raw[id]={initial:0,purchase:0,final:null}});return raw}
function setInventory(inv){localStorage.setItem('g71_inventory',JSON.stringify(inv))}
function use(inv,id,qty){inv[id]=(inv[id]||0)+qty}
function isHamb(id){return id&&id.startsWith('hamb-')}
function isSandwich(id){return ['sandwich-gourmet','sandwich-grill','sandwich-club','sandwich-atun','club-monster'].includes(id)}
function isPanini(id){return id&&id.startsWith('panini-')}
function isWaffle(id){return id&&id.startsWith('waffle-')}
function isCroissant(id){return id&&id.startsWith('croissant-')}
function inventoryUsage(orders){const out={};validOrders(orders).forEach(o=>(o.items||[]).forEach(i=>{const id=i.id, q=Number(i.qty||0); if(!q)return;
  if(isHamb(id)){use(out,'hamburguesas',(id==='hamb-monster-doble'?2:id==='hamb-monster-triple'?3:1)*q);use(out,'bollos',q)}
  if(['bolognesa','sandwich-grill','panini-mediterraneo'].includes(id))use(out,'hamburguesas',q);
  if(['papas-monster','ensalada-suprema-arrachera','panini-ranch-arrachera'].includes(id))use(out,'arrachera',q);
  if(['ensalada-hawaiana','ensalada-cesar','croissant-chicken','sandwich-gourmet','club-monster','fetuccini','panini-turco','panini-hawaiano'].includes(id))use(out,'pechuga',q);
  if(isSandwich(id))use(out,'panCaja',q);
  if(isWaffle(id))use(out,'waffles',(id==='waffle-club'||id==='waffle-gold'?2:1)*q);
  if(isPanini(id))use(out,'paniniInv',q);
  if(['bolognesa','fetuccini'].includes(id))use(out,'pastasInv',q);
  if(['croissant-atun','sandwich-atun'].includes(id))use(out,'atunInv',q);
  if(isCroissant(id)||['cuernito-cajeta','cuernito-nutella'].includes(id))use(out,'cuernitos',q);
  if(['refresco','coca-zero'].includes(id))use(out,'refrescosInv',q);
  if(id==='agua-bonafont')use(out,'bonafontInv',q);
  if(id==='fuze-tea')use(out,'fuzeTeaInv',q);
  if(id==='frappe-ferrero')use(out,'ferreroInv',q);
  (i.extras||[]).forEach(e=>{if(e.name==='Arrachera')use(out,'arrachera',q); if(e.name==='Pollo')use(out,'pechuga',q)});
}));return out}
function buildInventorySnapshot(orders){const inv=getInventory(), sold=inventoryUsage(orders), rows={};INV_ITEMS.forEach(([id,name])=>{const r=inv[id]||{initial:0,purchase:0,final:null};const initial=Number(r.initial||0), purchase=Number(r.purchase||0), vendido=Number(sold[id]||0), esperado=initial+purchase-vendido, final=(r.final===null||r.final===undefined)?esperado:Number(r.final||0);rows[id]={name,initial,purchase,vendido,esperado,final,diff:final-esperado}});return rows}
function carryInventoryForward(snapshot){const next={};INV_ITEMS.forEach(([id])=>{const row=snapshot[id];const start=row?Number(row.final||0):0;next[id]={initial:start,purchase:0,final:start}});setInventory(next)}
function originSums(orders){const valid=validOrders(orders), groups={mesa:0,llevar:0,didi:0,uber:0,personal:0};valid.forEach(o=>groups[o.origin]=(groups[o.origin]||0)+Number(o.total||0));groups.total=Object.values(groups).reduce((a,b)=>a+b,0);groups.count=valid.length;groups.errors=(orders||[]).filter(isError).length;return groups}
function archiveCard(a){const g=originSums(a.orders||[]);return `<div class="archiveCard"><div class="row between"><div><h3>📅 ${new Date(a.closedAt).toLocaleDateString()}</h3><small>Cerrado: ${new Date(a.closedAt).toLocaleString()}</small></div><button data-archive-detail="${a.id}">Ver detalles</button></div><div class="archiveGrid"><div class="archiveStat"><small>Total</small><b>${money(g.total)}</b></div><div class="archiveStat"><small>🛵 Uber</small><b>${money(g.uber)}</b></div><div class="archiveStat"><small>🛵 DiDi</small><b>${money(g.didi)}</b></div><div class="archiveStat"><small>🪑 Mesas</small><b>${money(g.mesa)}</b></div><div class="archiveStat"><small>🥡 Para llevar</small><b>${money(g.llevar)}</b></div><div class="archiveStat"><small>👤 Personal</small><b>${money(g.personal)}</b></div><div class="archiveStat"><small>Pedidos</small><b>${g.count}</b></div><div class="archiveStat"><small>Errores</small><b>${g.errors}</b></div></div></div>`}
function renderAdminHome(){if(!$('screenArchives'))return;$('screenArchives').innerHTML=`<div class="panel"><div class="row between"><h2>🔐 Administración</h2><button id="backClose">Volver al corte</button></div><p class="mut">Sección protegida para cierres e inventario.</p><div class="adminMenu"><button id="adminHistory">📊 Historial de cierres</button><button id="adminInventory">📦 Inventario</button></div></div>`;$('backClose').onclick=()=>show('screenClose','tabClose');$('adminHistory').onclick=renderArchiveCards;$('adminInventory').onclick=renderInventory}
function renderArchiveCards(){const list=state.archives||[];$('screenArchives').innerHTML=`<div class="panel"><div class="row between"><h2>📊 Historial de cierres</h2><button id="adminBack">Volver</button></div>${list.length?list.map(archiveCard).join(''):'<div class="empty">No hay cortes guardados.</div>'}</div>`;$('adminBack').onclick=renderAdminHome;document.querySelectorAll('[data-archive-detail]').forEach(b=>b.onclick=()=>renderArchiveDetail(Number(b.dataset.archiveDetail)))}
function inventoryTableFromSnapshot(snapshot){if(!snapshot)return '';return `<div class="accountBlock"><h4>📦 Inventario del cierre</h4><div class="inventoryWrap"><table class="inventoryTable"><thead><tr><th>Producto</th><th>Inicial</th><th>Compra</th><th>Vendido</th><th>Esperado</th><th>Final</th><th>Dif.</th></tr></thead><tbody>${INV_ITEMS.map(([id,name])=>{const r=snapshot[id]||{};const d=Number(r.diff||0);return `<tr><td>${name}</td><td>${r.initial||0}</td><td>${r.purchase||0}</td><td>${r.vendido||0}</td><td>${r.esperado||0}</td><td>${r.final||0}</td><td class="${d<0?'diffNeg':d>0?'diffPos':'diffZero'}">${d}</td></tr>`}).join('')}</tbody></table></div></div>`}
function renderArchiveDetail(id){const a=(state.archives||[]).find(x=>x.id===id);if(!a)return;const g=originSums(a.orders||[]);$('screenArchives').innerHTML=`<div class="panel"><div class="row between"><h2>📅 ${new Date(a.closedAt).toLocaleDateString()}</h2><div class="row"><button id="archiveBack">Volver</button><button class="danger" data-del-archive="${a.id}">Borrar respaldo</button></div></div><div class="archiveGrid"><div class="archiveStat"><small>Total</small><b>${money(g.total)}</b></div><div class="archiveStat"><small>🛵 Uber</small><b>${money(g.uber)}</b></div><div class="archiveStat"><small>🛵 DiDi</small><b>${money(g.didi)}</b></div><div class="archiveStat"><small>🪑 Mesas</small><b>${money(g.mesa)}</b></div><div class="archiveStat"><small>🥡 Para llevar</small><b>${money(g.llevar)}</b></div><div class="archiveStat"><small>👤 Personal</small><b>${money(g.personal)}</b></div><div class="archiveStat"><small>Pedidos</small><b>${g.count}</b></div><div class="archiveStat"><small>Errores</small><b>${g.errors}</b></div></div>${renderProductCounts(a.orders)}${renderErrors(a.orders)}${inventoryTableFromSnapshot(a.inventory)}${(a.orders||[]).map(o=>`<div class="accountBlock ${isError(o)?'orderError':''}"><h4>#${String(o.id).padStart(3,'0')} · ${orderPlace(o)} · ${money(o.total)}</h4><small>${new Date(o.created).toLocaleTimeString()} · ${o.status}${isError(o)?' · '+(o.errorReason||'Sin motivo')+' · '+(o.errorEmployee||'Sin responsable'):''}${o.adminEdited?' · Editado por administrador':''}</small>${groupedList(o.items)}${o.origin==='llevar'?`<ul><li>Envase x${packagingQty(o.items)} (${money(packagingTotal(o.items))})</li></ul>`:''}${o.notes?`<p>${o.notes}</p>`:''}${o.adminEdited?`<p class="mut">${o.adminEditNote||'Editado después del cierre'}${o.adminEditedAt?' · '+new Date(o.adminEditedAt).toLocaleString():''}</p>`:''}${!isError(o)?`<button data-archive-edit="${a.id}|${o.id}">Editar pedido cerrado</button>`:''}</div>`).join('')}</div>`;$('archiveBack').onclick=renderArchiveCards;document.querySelectorAll('[data-del-archive]').forEach(b=>b.onclick=()=>deleteArchive(Number(b.dataset.delArchive)));document.querySelectorAll('[data-archive-edit]').forEach(b=>b.onclick=()=>{const [aid,oid]=b.dataset.archiveEdit.split('|').map(Number);editOrder(oid,aid)})}
function renderInventory(keepPosition){
const restore=keepPosition||{};
const inv=getInventory(), sold=inventoryUsage(state.orders);
$('screenArchives').innerHTML=`<div class="panel"><div class="row between"><h2>📦 Inventario</h2><button id="adminBack">Volver</button></div><p class="mut">Inicial y Final pueden ajustarse con botones. Vendido se calcula automáticamente con los pedidos correctos del día.</p><div class="inventoryWrap"><table class="inventoryTable"><thead><tr><th>Producto</th><th>Inicial</th><th>Compra</th><th>Vendido</th><th>Esperado</th><th>Final</th><th>Dif.</th></tr></thead><tbody>${INV_ITEMS.map(([id,name])=>{const r=inv[id]||{initial:0,purchase:0,final:null};const initial=Number(r.initial||0), purchase=Number(r.purchase||0), vendido=Number(sold[id]||0), esperado=initial+purchase-vendido, final=(r.final===null||r.final===undefined)?esperado:Number(r.final||0), diff=final-esperado;return `<tr><td>${name}</td><td><div class="stepper"><button data-inv="${id}" data-field="initial" data-delta="-1">−</button><span>${initial}</span><button data-inv="${id}" data-field="initial" data-delta="1">+</button></div></td><td><div class="stepper"><button data-inv="${id}" data-field="purchase" data-delta="-1">−</button><span>${purchase}</span><button data-inv="${id}" data-field="purchase" data-delta="1">+</button></div></td><td>${vendido}</td><td>${esperado}</td><td><div class="stepper"><button data-inv="${id}" data-field="final" data-delta="-1" data-base="${final}">−</button><span>${final}</span><button data-inv="${id}" data-field="final" data-delta="1" data-base="${final}">+</button></div></td><td class="${diff<0?'diffNeg':diff>0?'diffPos':'diffZero'}">${diff}</td></tr>`}).join('')}</tbody></table></div></div>`;
$('adminBack').onclick=renderAdminHome;
if(restore.windowY!==undefined||restore.screenY!==undefined||restore.tableY!==undefined){setTimeout(()=>{if(restore.windowY!==undefined)window.scrollTo(0,restore.windowY);if($('screenArchives')&&restore.screenY!==undefined)$('screenArchives').scrollTop=restore.screenY;const wrap=document.querySelector('#screenArchives .inventoryWrap');if(wrap&&restore.tableY!==undefined)wrap.scrollTop=restore.tableY;},0)}
document.querySelectorAll('[data-inv]').forEach(b=>b.onclick=()=>{flash(b);const currentWrap=document.querySelector('#screenArchives .inventoryWrap');const keep={windowY:window.scrollY,screenY:$('screenArchives')?$('screenArchives').scrollTop:0,tableY:currentWrap?currentWrap.scrollTop:0};const inv=getInventory(), id=b.dataset.inv, f=b.dataset.field, delta=Number(b.dataset.delta);if(!inv[id])inv[id]={initial:0,purchase:0,final:null};let cur=f==='final'?(inv[id].final===null||inv[id].final===undefined?Number(b.dataset.base||0):Number(inv[id].final||0)):Number(inv[id][f]||0);cur=Math.max(0,cur+delta);inv[id][f]=cur;setInventory(inv);renderInventory(keep)})}
function renderTabs(){[['tabNew','screenNew'],['tabActive','screenActive'],['tabClose','screenClose']].forEach(([b,s])=>$(b).onclick=()=>show(s,b));if($('archivesBtn')){$('archivesBtn').textContent='Administración';$('archivesBtn').onclick=()=>{if(ownerPass()){renderAdminHome();show('screenArchives','tabClose')}}}if($('backClose'))$('backClose').onclick=()=>show('screenClose','tabClose')}
function ownerPass(){const p=prompt('Contraseña de administración:');return p===OWNER_PASSWORD}
function closeDay(){if(!state.orders.length){alert('No hay pedidos para cerrar.');return}if(!confirm('Se guardará el corte de hoy con inventario y se limpiará la pantalla para empezar de nuevo en #001. ¿Cerrar día?'))return;const now=new Date();const snapshot=buildInventorySnapshot(state.orders);const archive={id:Date.now(),closedAt:now.toISOString(),label:now.toLocaleDateString(),orders:JSON.parse(JSON.stringify(state.orders)),inventory:snapshot,summary:buildSummary(state.orders,'Corte guardado',null)};state.archives.unshift(archive);carryInventoryForward(snapshot);state.orders=[];state.seq=1;save();renderOrders();renderSummary();if($('screenArchives')&&$('screenArchives').classList.contains('on'))renderAdminHome();$('next').textContent='#001';alert('Corte guardado. Ya puedes iniciar el nuevo día desde #001. El inventario final pasó como inicial del nuevo día.')}
function renderArchives(){renderArchiveCards()}
$('resetCounter').onclick=()=>{if(confirm('Esto reinicia el número de pedido a #001. No borra pedidos guardados.')){state.seq=1;save();$('next').textContent='#001';renderSummary()}};$('closeDay').onclick=closeDay;setInterval(renderOrders,60000);init();
})();
