(function(){
const OWNER_PASSWORD='7171';
const APP={packagingFee:5,origins:[['mesa','🪑 Mesa'],['llevar','🥡 Para llevar'],['didi','🛵 DiDi Food'],['uber','🛵 Uber Eats'],['personal','👤 Personal']],employees:['Kevin','Bere','Alex','Elias'],quick:['Sin azúcar','Sin cebolla','Sin jitomate','Sin lechuga','Extra queso','Poco hielo','Sin crema'],extras:{comida:[['Aguacate',20],['Queso',20],['Jamón',20],['Tocino',20],['Piña',20],['Aderezo',20],['Huevo',20],['Pollo',89],['Arrachera',89]],desayuno:[['Queso',20],['Jamón',20],['Tocino',20],['Huevo',20],['Pollo',89],['Arrachera',89]],ensalada:[['Aguacate',20],['Aderezo',20],['Pollo',89],['Arrachera',89]],hamburguesa:[['Queso',20],['Tocino',20],['Piña',20],['Aguacate',20],['Huevo',20],['Pollo',89],['Arrachera',89]],waffle:[['Queso',20],['Jamón',20],['Tocino',20],['Huevo',20],['Pollo',89],['Arrachera',89]]}};
const raw = window.GOLD71_MENU_RAW || [];
const PRODUCTS=raw.map(([id,name,category,localPrice,appPrice,appAvailable])=>({id,name,category,localPrice,appPrice,appAvailable:!!appAvailable}));
const $=id=>document.getElementById(id);const money=n=>'$'+Number(n||0).toFixed(0);const labels=Object.fromEntries(APP.origins);const fav=['cafe-americano','capuchino-grande','lechero','frappe-oreo','panini-turco','hamb-regia-green','croissant-chicken','limonada-fresa'];
let state={origin:'mesa',mesa:1,employee:null,account:1,category:'Favoritos',cart:[],orders:JSON.parse(localStorage.getItem('g71_orders')||'[]'),archives:JSON.parse(localStorage.getItem('g71_archives')||'[]'),seq:Number(localStorage.getItem('g71_seq')||1),target:null,editId:null,returnScreen:'screenActive'};
function save(){localStorage.setItem('g71_orders',JSON.stringify(state.orders));localStorage.setItem('g71_seq',state.seq);localStorage.setItem('g71_archives',JSON.stringify(state.archives||[]))}
function recalcCurrentTakeoutTotals(){let changed=false;state.orders.forEach(o=>{if(o.origin==='llevar'){const t=(o.items||[]).reduce((a,i)=>a+itemTotal(i),0)+packagingTotal(o.items||[]);if(o.total!==t){o.total=t;changed=true}}});if(changed)save()}
function isDiscountExcluded(p){return ['hamb-monster-doble','hamb-monster-triple','malteada-monster','refresco','coca-zero','fuze-tea','agua-bonafont'].includes(p.id)}function price(p){const base=state.origin==='personal'?p.localPrice:((state.origin==='didi'||state.origin==='uber')?p.appPrice:p.localPrice);return state.origin==='personal'&&!isDiscountExcluded(p)?Math.floor(base*0.5):base}function avail(p){return (state.origin==='didi'||state.origin==='uber')?p.appAvailable:p.localPrice!==null}
function init(){recalcCurrentTakeoutTotals();renderTabs();renderOrigin();renderTables();renderEmployees();renderCats();renderQuick();renderProducts();renderAccounts();renderCart();renderOrders();renderSummary();renderArchives();$('next').textContent='#'+String(state.seq).padStart(3,'0')}
function flash(el){if(!el)return;el.classList.remove('tapFlash');void el.offsetWidth;el.classList.add('tapFlash')}
function renderTabs(){[['tabNew','screenNew'],['tabActive','screenActive'],['tabClose','screenClose']].forEach(([b,s])=>$(b).onclick=()=>show(s,b));$('backClose').onclick=()=>show('screenClose','tabClose');$('archivesBtn').onclick=()=>{if(ownerPass())show('screenArchives','tabClose')}}function show(screen,btn){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('on'));$(screen).classList.add('on');document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('on'));$(btn).classList.add('on');renderOrders();renderSummary()}
function renderOrigin(){$('origin').innerHTML=APP.origins.map(([id,l])=>`<button class="${state.origin===id?'on':''}" data-origin="${id}">${l}</button>`).join('');document.querySelectorAll('[data-origin]').forEach(b=>b.onclick=()=>{flash(b);state.origin=b.dataset.origin;state.mesa=state.origin==='mesa'?(state.mesa||1):null;state.employee=state.origin==='personal'?(state.employee||APP.employees[0]):null;state.category='Favoritos';$('search').value='';renderOrigin();renderTables();renderEmployees();renderCats();renderProducts();renderAccounts();renderCart()})}
function renderTables(){$('tables').innerHTML=state.origin==='mesa'?Array.from({length:12},(_,i)=>`<button class="${state.mesa===i+1?'on':''}" data-mesa="${i+1}">Mesa ${i+1}</button>`).join(''):'';document.querySelectorAll('[data-mesa]').forEach(b=>b.onclick=()=>{flash(b);state.mesa=Number(b.dataset.mesa);renderTables();renderCart()})}function renderEmployees(){$('employees').innerHTML=state.origin==='personal'?'<p class="mut" style="width:100%;margin:4px 0 0">Empleado:</p>'+APP.employees.map(n=>`<button class="${state.employee===n?'on':''}" data-emp="${n}">${n}</button>`).join(''):'';document.querySelectorAll('[data-emp]').forEach(b=>b.onclick=()=>{flash(b);state.employee=b.dataset.emp;renderEmployees();renderCart()})}
function renderAccounts(){$('accounts').innerHTML=Array.from({length:6},(_,i)=>`<button class="${state.account===i+1?'on':''}" data-acc="${i+1}">Cuenta ${i+1}</button>`).join('');document.querySelectorAll('[data-acc]').forEach(b=>b.onclick=()=>{flash(b);state.account=Number(b.dataset.acc);renderAccounts();renderCart()})}
const CATEGORY_ORDER=['Entradas','Huevos','Ensaladas','Croissants','Sándwiches','Pastas','Hamburguesas','Paninis','Postres','Cafés fríos y frappés','Cafés','Bebidas','Tés','Waffles salados','Waffles dulces'];
const CATEGORY_LABELS={
'Favoritos':'⭐ Favoritos',
'Entradas':'🍟 Entradas',
'Huevos':'🍳 Huevos',
'Ensaladas':'🥗 Ensaladas',
'Croissants':'🥐 Croissants',
'Sándwiches':'🥪 Sándwiches',
'Pastas':'🍝 Pastas',
'Hamburguesas':'🍔 Hamburguesas',
'Paninis':'🥖 Paninis',
'Postres':'🍰 Postres',
'Cafés fríos y frappés':'🧊 Cafés fríos',
'Cafés':'☕ Cafés calientes',
'Bebidas':'🥤 Bebidas',
'Tés':'🍵 Tés',
'Waffles salados':'🧇 Waffles salados',
'Waffles dulces':'🧇 Waffles dulces'
};
function catLabel(c){return CATEGORY_LABELS[c]||c}
function categories(){const available=[...new Set(PRODUCTS.filter(avail).map(p=>p.category))];return ['Favoritos',...CATEGORY_ORDER.filter(c=>available.includes(c)),...available.filter(c=>!CATEGORY_ORDER.includes(c)).sort()]}function renderCats(){$('cats').innerHTML=categories().map(c=>`<button class="${state.category===c?'on':''}" data-cat="${c}">${catLabel(c)}</button>`).join('');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{flash(b);state.category=b.dataset.cat;$('search').value='';renderCats();renderProducts()})}
function renderProducts(){const q=$('search').value.trim().toLowerCase();let list=PRODUCTS.filter(avail);if(q){list=list.filter(p=>p.name.toLowerCase().includes(q)||p.category.toLowerCase().includes(q))}else if(state.category==='Favoritos'){list=list.filter(p=>fav.includes(p.id))}else{list=list.filter(p=>p.category===state.category)}$('products').innerHTML=list.length?list.map(p=>`<button class="prod" data-prod="${p.id}">${p.name}<small>${catLabel(p.category)} · ${money(price(p))}</small></button>`).join(''):'<div class="empty">No hay productos con ese filtro.</div>';document.querySelectorAll('[data-prod]').forEach(b=>b.onclick=()=>{flash(b);openExtras(b.dataset.prod)})}
$('search').addEventListener('input',renderProducts);
function renderQuick(){$('quick').innerHTML=APP.quick.map(n=>`<button data-note="${n}">${n}</button>`).join('');document.querySelectorAll('[data-note]').forEach(b=>b.onclick=()=>{flash(b);$('notes').value=($('notes').value?$('notes').value+'; ':'')+b.dataset.note})}
function extrasFor(p){const c=p.category.toLowerCase();if(c.includes('caf')||c.includes('bebidas')||c.includes('tés'))return [];if(c.includes('hamburguesas'))return APP.extras.hamburguesa;if(c.includes('ensaladas'))return APP.extras.ensalada;if(c.includes('huevos'))return APP.extras.desayuno;if(c.includes('waffles salados'))return APP.extras.waffle;if(c.includes('croissants')||c.includes('sándwiches')||c.includes('sandwiches')||c.includes('paninis'))return APP.extras.comida;return []}
function openExtras(id){state.target=PRODUCTS.find(p=>p.id===id);const list=extrasFor(state.target);if(!list.length){addProduct(state.target,[]);return}$('extraTitle').textContent=state.target.name;$('extras').innerHTML=list.map(([n,p],i)=>`<label class="extra"><input type="checkbox" data-extra="${i}"><span>${n} +${money(p)}</span></label>`).join('');$('extraModal').dataset.kind=state.target.id;document.querySelectorAll('.extra').forEach(l=>l.onclick=()=>flash(l));$('extraModal').classList.add('on')}
$('extraCancel').onclick=()=>$('extraModal').classList.remove('on');$('extraAdd').onclick=()=>{const list=extrasFor(state.target);const extras=[...document.querySelectorAll('[data-extra]:checked')].map(x=>{const e=list[Number(x.dataset.extra)];return{name:e[0],price:e[1]}});addProduct(state.target,extras);$('extraModal').classList.remove('on')};
function addProduct(p,extras){const acc=state.account||1;const key=p.id+'|'+acc+'|'+extras.map(e=>e.name).join(',');const found=state.cart.find(i=>i.key===key);if(found)found.qty++;else state.cart.push({key,id:p.id,name:p.name,base:price(p),qty:1,extras,account:acc});renderCart()}
function currentLabel(){return state.origin==='mesa'?`🪑 Mesa ${state.mesa}`:(state.origin==='personal'?`👤 Personal · ${state.employee||'Sin nombre'}`:labels[state.origin])}function itemTotal(i){return (i.base+i.extras.reduce((a,e)=>a+e.price,0))*i.qty}function total(){let t=state.cart.reduce((a,i)=>a+itemTotal(i),0);if(state.origin==='llevar'&&state.cart.length)t+=packagingTotal(state.cart);return t}
function itemsByAccount(items){const g={};items.forEach(i=>{const a=i.account||1;(g[a]||(g[a]=[])).push(i)});return g}
function accountSubtotal(items,acc){return items.filter(i=>(i.account||1)===Number(acc)).reduce((a,i)=>a+itemTotal(i),0)}
function packagingQty(items){return (items||[]).reduce((a,i)=>a+(Number(i.qty)||0),0)}
function packagingTotal(items){return packagingQty(items)*APP.packagingFee}
function groupedList(items){const g=itemsByAccount(items);return Object.keys(g).sort((a,b)=>a-b).map(acc=>`<div class="accountBlock"><h4>Cuenta ${acc} · ${money(accountSubtotal(items,acc))}</h4><ul>${g[acc].map(i=>`<li>${i.qty} × ${i.name}${i.extras.length?' ('+i.extras.map(e=>e.name).join(', ')+')':''}</li>`).join('')}</ul></div>`).join('')}
function renderCart(){
  $('meta').textContent=currentLabel();
  renderAccounts();
  if(!state.cart.length){
    $('cart').innerHTML='<div class="empty">Agrega productos al pedido.</div>';
  }else{
    const g=itemsByAccount(state.cart);
    $('cart').innerHTML=Object.keys(g).sort((a,b)=>a-b).map(acc=>`<div class="accountBlock"><h4>Cuenta ${acc} · ${money(accountSubtotal(state.cart,acc))}</h4>${g[acc].map(i=>{const idx=state.cart.indexOf(i);return `<div class="item"><b>${i.qty} × ${i.name}</b><small>${i.extras.length?i.extras.map(e=>e.name).join(', ')+' · ':''}${money(itemTotal(i))}</small><div class="ctrl"><button data-plus="${idx}">+</button><button data-minus="${idx}">−</button><button data-del="${idx}">Eliminar</button><button data-move="${idx}">Cambiar cuenta</button></div></div>`}).join('')}</div>`).join('')+(state.origin==='llevar'?`<div class="item"><b>Envase x${packagingQty(state.cart)}</b><small>${money(packagingTotal(state.cart))}</small></div>`:'');
  }
  document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>{flash(b);state.cart[Number(b.dataset.plus)].qty++;renderCart()});
  document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>{flash(b);const i=Number(b.dataset.minus);state.cart[i].qty--;if(state.cart[i].qty<1)state.cart.splice(i,1);renderCart()});
  document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{flash(b);state.cart.splice(Number(b.dataset.del),1);renderCart()});
  document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{flash(b);const i=Number(b.dataset.move);const n=Number(prompt('Mover a cuenta (1-6):',state.cart[i].account||1));if(n>=1&&n<=6){state.cart[i].account=n;state.cart[i].key=state.cart[i].id+'|'+n+'|'+state.cart[i].extras.map(e=>e.name).join(',');renderCart()}});
  $('total').textContent=money(total())
}
$('clear').onclick=()=>{flash($('clear'));state.cart=[];state.editId=null;state.account=1;$('notes').value='';renderAccounts();renderCart();$('send').textContent='Enviar pedido'};$('send').onclick=()=>{flash($('send'));if(!state.cart.length){alert('Agrega al menos un producto.');return}if(state.origin==='personal'&&!state.employee){alert('Selecciona quién del personal está pidiendo.');return}const payload={origin:state.origin,mesa:state.mesa,employee:state.employee,items:JSON.parse(JSON.stringify(state.cart)),notes:$('notes').value,total:total()};if(state.editId){const o=state.orders.find(x=>x.id===state.editId);Object.assign(o,payload);state.editId=null;$('send').textContent='Enviar pedido';}else{state.orders.unshift({id:state.seq++,created:Date.now(),status:'Pendiente',...payload});}state.cart=[];state.account=1;$('notes').value='';save();init();show('screenActive','tabActive')};
function orderPlace(o){return o.origin==='mesa'?'🪑 Mesa '+o.mesa:(o.origin==='personal'?'👤 Personal · '+(o.employee||'Sin nombre'):labels[o.origin])}function minutes(t){return Math.max(0,Math.floor((Date.now()-t)/60000))}function renderOrders(){const active=state.orders.filter(o=>o.status!=='Entregado');$('orders').innerHTML=active.length?active.map(o=>`<div class="order"><h3>#${String(o.id).padStart(3,'0')} · ${orderPlace(o)}</h3><span class="pill">${o.status}</span> <span class="pill">${minutes(o.created)} min</span> <span class="pill">${money(o.total)}</span>${groupedList(o.items)}${o.origin==='llevar'?`<ul><li>Envase x${packagingQty(o.items)} (${money(packagingTotal(o.items))})</li></ul>`:''}${o.notes?`<p>${o.notes}</p>`:''}<button data-edit="${o.id}">Editar</button><button class="next" data-next="${o.id}">${o.status} →</button></div>`).join(''):'<div class="empty">Sin pedidos activos.</div>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editOrder(Number(b.dataset.edit)));document.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>{const o=state.orders.find(x=>x.id===Number(b.dataset.next));o.status={Pendiente:'Preparando',Preparando:'Listo',Listo:'Entregado'}[o.status]||'Entregado';save();renderOrders();renderSummary()})}
function buildSummary(orders,title,seqText){const groups={mesa:[],llevar:[],didi:[],uber:[],personal:[]};orders.forEach(o=>(groups[o.origin]||(groups[o.origin]=[])).push(o));let grand=0,txt=`Gold 71 Café · Galaxia OS\n${title}\n\n`;APP.origins.forEach(([id,l])=>{const sum=(groups[id]||[]).reduce((a,o)=>a+o.total,0);grand+=sum;txt+=`${l}: ${(groups[id]||[]).length} pedidos · ${money(sum)}\n`});txt+=`\nTOTAL: ${money(grand)}`;if(seqText)txt+=`\n${seqText}`;return txt}
function productCounts(orders){const counts={};orders.forEach(o=>o.items.forEach(i=>{const name=i.name+(i.extras&&i.extras.length?' ('+i.extras.map(e=>e.name).join(', ')+')':'');counts[name]=(counts[name]||0)+i.qty}));return Object.entries(counts).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))}
function renderProductCounts(orders){const counts=productCounts(orders);return counts.length?`<div class="accountBlock"><h4>Productos vendidos</h4><ul>${counts.map(([n,q])=>`<li>${q} × ${n}</li>`).join('')}</ul></div>`:''}
function renderSummary(){$('summary').textContent=buildSummary(state.orders,'Corte del día',`Siguiente pedido: #${String(state.seq).padStart(3,'0')}`);$('history').innerHTML=renderProductCounts(state.orders)+state.orders.map(o=>`<div class="historyItem"><b>#${String(o.id).padStart(3,'0')} · ${orderPlace(o)} · ${money(o.total)}</b><br><small>${new Date(o.created).toLocaleTimeString()} · ${o.status}</small>${groupedList(o.items)}${o.origin==='llevar'?`<ul><li>Envase x${packagingQty(o.items)} (${money(packagingTotal(o.items))})</li></ul>`:''}${o.notes?`<p>${o.notes}</p>`:''}<button data-edit="${o.id}">Editar</button></div>`).join('');document.querySelectorAll('#history [data-edit]').forEach(b=>b.onclick=()=>editOrder(Number(b.dataset.edit)))}

function editOrder(id){const o=state.orders.find(x=>x.id===id);if(!o)return;state.editId=id;state.origin=o.origin;state.mesa=o.mesa||null;state.employee=o.employee||null;state.cart=JSON.parse(JSON.stringify(o.items)).map(i=>({...i,account:i.account||1,key:i.key||i.id+'|'+(i.account||1)+'|'+(i.extras||[]).map(e=>e.name).join(',')}));state.account=1;$('notes').value=o.notes||'';state.category='Favoritos';$('search').value='';$('send').textContent='Guardar cambios';renderOrigin();renderTables();renderEmployees();renderCats();renderProducts();renderCart();show('screenNew','tabNew')}
function ownerPass(){const p=prompt('Contraseña para historial de cierres:');return p===OWNER_PASSWORD}
function closeDay(){if(!state.orders.length){alert('No hay pedidos para cerrar.');return}if(!confirm('Se guardará el corte de hoy en Historial de cierres y se limpiará la pantalla para empezar de nuevo en #001. ¿Cerrar día?'))return;const now=new Date();const archive={id:Date.now(),closedAt:now.toISOString(),label:now.toLocaleDateString(),orders:JSON.parse(JSON.stringify(state.orders)),summary:buildSummary(state.orders,'Corte guardado',null)};state.archives.unshift(archive);state.orders=[];state.seq=1;save();renderOrders();renderSummary();renderArchives();$('next').textContent='#001';alert('Corte guardado. Ya puedes iniciar el nuevo día desde #001.')}
function renderArchives(){if(!$('archives'))return;const list=state.archives||[];$('archives').innerHTML=list.length?list.map(a=>`<div class="historyItem"><div class="row between"><div><b>${new Date(a.closedAt).toLocaleDateString()} · ${a.orders.length} pedidos</b><br><small>Cerrado: ${new Date(a.closedAt).toLocaleString()}</small></div><button class="danger" data-del-archive="${a.id}">Borrar respaldo</button></div><pre>${buildSummary(a.orders,'Corte guardado',null)}</pre>${renderProductCounts(a.orders)}${a.orders.map(o=>`<div class="accountBlock"><h4>#${String(o.id).padStart(3,'0')} · ${orderPlace(o)} · ${money(o.total)}</h4><small>${new Date(o.created).toLocaleTimeString()} · ${o.status}</small>${groupedList(o.items)}${o.origin==='llevar'?`<ul><li>Envase x${packagingQty(o.items)} (${money(packagingTotal(o.items))})</li></ul>`:''}${o.notes?`<p>${o.notes}</p>`:''}</div>`).join('')}</div>`).join(''):'<div class="empty">No hay cortes guardados.</div>';document.querySelectorAll('[data-del-archive]').forEach(b=>b.onclick=()=>deleteArchive(Number(b.dataset.delArchive)))}
function deleteArchive(id){if(!ownerPass())return;if(!confirm('Esto sí borra definitivamente este respaldo. ¿Seguro?'))return;state.archives=(state.archives||[]).filter(a=>a.id!==id);save();renderArchives()}
$('resetCounter').onclick=()=>{if(confirm('Esto reinicia el número de pedido a #001. No borra pedidos guardados.')){state.seq=1;save();$('next').textContent='#001';renderSummary()}};$('closeDay').onclick=closeDay;setInterval(renderOrders,60000);init();
})();
