// Menú y precios de Gold 71 Café · Galaxia OS
// Formato: [id, nombre, categoría, precioLocal, precioApps, disponibleEnApps]
// Si precioApps es null o disponibleEnApps es 0, no aparece en DiDi/Uber.
window.GOLD71_MENU_RAW = [
// Cafés calientes
['cafe-americano','Café americano','Cafés',45,49,1],
['americano-refill','Refill americano','Cafés',18,null,0],
['descafeinado','Descafeinado','Cafés',46,50,1],
['descafeinado-refill','Refill descafeinado','Cafés',18,null,0],
['espresso','Espresso','Cafés',45,null,0],
['espresso-cortado','Espresso cortado','Cafés',49,null,0],
['espresso-doble','Espresso doble','Cafés',54,null,0],
['capuchino-chico','Capuchino chico','Cafés',49,null,0],
['capuchino-grande','Capuchino grande natural','Cafés',59,67,1],
['capuchino-grande-cajeta','Capuchino grande cajeta','Cafés',59,67,1],
['capuchino-grande-moka','Capuchino grande moka','Cafés',59,67,1],
['capuchino-grande-rompope','Capuchino grande rompope','Cafés',59,67,1],
['lechero','Lechero','Cafés',59,67,1],
['lechero-caramel','Lechero Caramel','Cafés',62,null,0],
['chocolate-caliente','Chocolate caliente','Cafés',56,56,1],
// Cafés fríos y frappés
['affogato','Affogato','Cafés fríos y frappés',69,null,0],
['espresso-rocas','Espresso en las rocas','Cafés fríos y frappés',54,null,0],
['latte-frio','Latte frío','Cafés fríos y frappés',59,69,1],
['latte-caramel-frio','Latte caramel frío','Cafés fríos y frappés',65,null,0],
['latte-milk-frio','Latte milk frío','Cafés fríos y frappés',65,null,0],
['latte-bombon-frio','Latte bombón frío','Cafés fríos y frappés',65,null,0],
['latte-tiramisu-frio','Latte tiramisú frío','Cafés fríos y frappés',65,null,0],
['latte-honey','Latte honey','Cafés fríos y frappés',65,null,0],
['frappe-oreo','Frappé Oreo','Cafés fríos y frappés',89,102,1],
['frappe-nutella','Frappé Nutella','Cafés fríos y frappés',98,115,1],
['frappe-mazapan','Frappé Mazapán','Cafés fríos y frappés',98,null,0],
['frappe-taro','Frappé Taro','Cafés fríos y frappés',98,null,0],
['frappe-ferrero','Frappé Ferrero','Cafés fríos y frappés',98,null,0],
['frappe-capuchino','Frappé Capuchino natural','Cafés fríos y frappés',79,92,1],
['frappe-capuchino-cajeta','Frappé Capuchino cajeta','Cafés fríos y frappés',79,92,1],
['frappe-capuchino-moka','Frappé Capuchino moka','Cafés fríos y frappés',79,92,1],
['frappe-capuchino-rompope','Frappé Capuchino rompope','Cafés fríos y frappés',79,92,1],
['frappe-capuchino-fresa','Frappé Capuchino fresa','Cafés fríos y frappés',79,92,1],
['frappe-capuchino-caramelo','Frappé Capuchino caramelo','Cafés fríos y frappés',79,92,1],
// Bebidas
['flotante','Flotante','Bebidas',59,null,0],
['esquimo','Esquimo fresa','Bebidas',69,78,1],
['esquimo-vainilla','Esquimo vainilla','Bebidas',69,78,1],
['esquimo-chocolate','Esquimo chocolate','Bebidas',69,78,1],
['chocomilk','Chocomilk','Bebidas',59,67,1],
['chocomilk-fresa','Chocomilk con fresa','Bebidas',69,null,0],
['smoothie-pina-colada','Smoothie Piña Colada','Bebidas',69,78,1],
['malteada','Malteada fresa','Bebidas',89,null,0],
['malteada-vainilla','Malteada vainilla','Bebidas',89,null,0],
['malteada-chocolate','Malteada chocolate','Bebidas',89,null,0],
['malteada-oreo','Malteada Oreo','Bebidas',92,102,1],
['malteada-monster','Malteada Monster','Bebidas',149,null,0],
['vaso-leche','Vaso con leche','Bebidas',25,null,0],
['refresco','Refresco','Bebidas',32,35,1],
['coca-zero','Coca Zero','Bebidas',32,35,1],
['fuze-tea','Fuze Tea','Bebidas',32,35,1],
['agua-bonafont','Agua Bonafont','Bebidas',19,null,0],
['maracuya','Maracuyá','Bebidas',49,null,0],
['limonada','Limonada','Bebidas',42,49,1],
['limonada-mineral','Limonada mineral','Bebidas',46,null,0],
['limonada-fresa','Limonada fresa','Bebidas',49,54,1],
['maracuya-fresa','Maracuyá fresa','Bebidas',49,null,0],
['horchata','Horchata','Bebidas',42,null,0],
// Tés
['te-caliente','Té caliente','Tés',45,49,1],
['te-gourmet-helado','Té gourmet frío','Tés',59,69,1],
// Croissants
['croissant-especial','Croissant Especial','Croissants',99,null,0],
['croissant-chicken','Croissant Chicken','Croissants',109,118,1],
['croissant-libano','Croissant Líbano','Croissants',99,115,1],
['croissant-atun','Croissant Atún','Croissants',89,null,0],
['croissant-campesino','Croissant Campesino','Croissants',89,null,0],
// Sándwiches
['sandwich-gourmet','Sándwich Gourmet','Sándwiches',109,128,1],
['sandwich-grill','Sándwich Grill','Sándwiches',136,null,0],
['sandwich-club','Sándwich Club','Sándwiches',99,115,1],
['sandwich-atun','Sándwich Atún','Sándwiches',99,null,0],
['club-monster','Club Monster','Sándwiches',149,null,0],
// Hamburguesas
['hamb-sencilla-queso','Hamburguesa sencilla con queso','Hamburguesas',129,149,1],
['hamb-regia-green','Hamburguesa Regia Green','Hamburguesas',149,179,1],
['hamb-angus-hawai','Hamburguesa Angus Hawai','Hamburguesas',149,179,1],
['hamb-gold-tocino','Hamburguesa Gold Tocino','Hamburguesas',149,179,1],
['hamb-bbq','Hamburguesa Salsa BBQ','Hamburguesas',139,162,1],
['hamb-monster-clasica','Hamburguesa Monster Clásica','Hamburguesas',179,215,1],
['hamb-monster-cheese','Hamburguesa Monster Cheese','Hamburguesas',189,null,0],
['hamb-monster-champion','Hamburguesa Monster Champion','Hamburguesas',189,null,0],
['hamb-monster-doble','Hamburguesa Monster Doble','Hamburguesas',279,null,0],
['hamb-monster-triple','Hamburguesa Monster Triple','Hamburguesas',349,null,0],
// Paninis
['panini-freddo','Panini Freddo','Paninis',119,142,1],
['panini-turco','Panini Turco','Paninis',149,167,1],
['panini-hawaiano','Panini Hawaiano','Paninis',167,189,1],
['panini-ranch-arrachera','Panini Ranch Arrachera','Paninis',189,199,1],
['panini-mediterraneo','Panini Mediterráneo','Paninis',167,null,0],
// Ensaladas
['ensalada-hawaiana','Ensalada Hawaiana','Ensaladas',145,169,1],
['ensalada-suprema-arrachera','Ensalada Suprema Arrachera','Ensaladas',162,189,1],
['ensalada-cesar','Ensalada César','Ensaladas',129,null,0],
// Pastas
['bolognesa','Spaguetti a la Bolognesa','Pastas',167,189,1],
['fetuccini','Fetuccini Gold','Pastas',169,199,1],
// Huevos
['huevos-al-gusto','Huevos al gusto','Huevos',75,78,1],
['omelette','Omelette','Huevos',75,null,0],
['omelette-gold','Omelette Gold','Huevos',95,null,0],
['omelette-champion','Omelette Champion','Huevos',95,null,0],
// Entradas
['aros-cebolla','Aros de cebolla','Entradas',89,null,0],
['papas-francesa','Papas a la francesa','Entradas',69,null,0],
['papas-monster','Papas Monster','Entradas',149,null,0],
['rollitos-jamon','Rollitos de jamón','Entradas',59,null,0],
['fajitas-arrachera','Fajitas de arrachera','Entradas',120,null,0],
['entrada-gold','Entrada Gold','Entradas',149,null,0],
// Waffles dulces
['waffle-caramelo','Waffle Caramelo','Waffles dulces',89,null,0],
['waffle-cajeta','Waffle Cajeta','Waffles dulces',89,null,0],
['waffle-lechera','Waffle Lechera','Waffles dulces',89,null,0],
['waffle-miel','Waffle Miel','Waffles dulces',89,null,0],
['waffle-nutella','Waffle Nutella','Waffles dulces',99,null,0],
['waffle-gold','Waffle Gold','Waffles dulces',129,null,0],
// Waffles salados
['waffle-huevo-tocino','Waffle Huevo y tocino','Waffles salados',109,null,0],
['waffle-jamon-queso','Waffle Jamón y queso','Waffles salados',109,null,0],
['waffle-club','Club Waffle','Waffles salados',149,null,0],
// Postres
['flan-napolitano','Flan Napolitano','Postres',72,null,0],
['cuernito-cajeta','Cuernito Cajeta','Postres',59,59,1],
['cuernito-nutella','Cuernito Nutella','Postres',69,null,0]
];;
