(function(){
const CONFIG=window.GOLD71_CONFIG||{};
const OWNER_PASSWORD=CONFIG.ownerPassword||'7171';
const APP=CONFIG.app||{};
const raw = window.GOLD71_MENU_RAW || [];
const PRODUCTS=raw.map(([id,name,category,localPrice,appPrice,appAvailable])=>({id,name,category,localPrice,appPrice,appAvailable:!!appAvailable}));
const $=id=>document.getElementById(id);const money=n=>'$'+Number(n||0).toFixed(0);const labels=Object.fromEntries(APP.origins||[]);const ORIGIN_COLORS={mesa:'#8b5cf6',llevar:'#ef4444',uber:'#065f46',didi:'#f97316',personal:'#3b82f6'};const isError=o=>o&&o.status==='Error de pedido';const validOrders=orders=>(orders||[]).filter(o=>!isError(o));const fav=CONFIG.favorites||[];
let state={origin:'mesa',mesa:1,employee:null,account:1,category:'Favoritos',cart:[],packagingManual:false,packagingCount:0,discountAmount:0,orders:JSON.parse(localStorage.getItem('g71_orders')||'[]'),archives:JSON.parse(localStorage.getItem('g71_archives')||'[]'),seq:Number(localStorage.getItem('g71_seq')||1),target:null,editId:null,returnScreen:'screenActive',editArchiveId:null};
function save(){localStorage.setItem('g71_orders',JSON.stringify(state.orders));localStorage.setItem('g71_seq',state.seq);localStorage.setItem('g71_archives',JSON.stringify(state.archives||[]))}
function recalcCurrentTakeoutTotals(){let changed=false;state.orders.forEach(o=>{if(o.origin==='llevar'||o.origin==='personal'){const qty=orderPackagingQty(o);const t=Math.max(0,(o.items||[]).reduce((a,i)=>a+itemTotal(i),0)+qty*APP.packagingFee-Number(o.discountAmount||0));if(o.total!==t){o.total=t;changed=true}}});if(changed)save()}
function isDiscountExcluded(p){return ['hamb-monster-doble','hamb-monster-triple','malteada-monster','refresco','coca-zero','fuze-tea','agua-bonafont'].includes(p.id)}function price(p){const base=state.origin==='personal'?p.localPrice:((state.origin==='didi'||state.origin==='uber')?p.appPrice:p.localPrice);return state.origin==='personal'&&!isDiscountExcluded(p)?Math.floor(base*0.5):base}function avail(p){return (state.origin==='didi'||state.origin==='uber')?p.appAvailable:p.localPrice!==null}
function init(){recalcCurrentTakeoutTotals();renderTabs();renderOrigin();renderTables();renderEmployees();renderCats();renderQuick();renderProducts();renderAccounts();renderCart();renderOrders();renderSummary();renderArchives();$('next').textContent='#'+String(state.seq).padStart(3,'0')}
function flash(el){if(!el)return;el.classList.remove('tapFlash');void el.offsetWidth;el.classList.add('tapFlash')}
function renderTabs(){[['tabNew','screenNew'],['tabActive','screenActive'],['tabClose','screenClose']].forEach(([b,s])=>$(b).onclick=()=>show(s,b));$('backClose').onclick=()=>show('screenClose','tabClose');$('archivesBtn').onclick=()=>{if(ownerPass())show('screenArchives','tabClose')}}function show(screen,btn){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('on'));$(screen).classList.add('on');document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('on'));$(btn).classList.add('on');renderOrders();renderSummary()}
function renderOrigin(){$('origin').innerHTML=APP.origins.map(([id,l])=>`<button class="${state.origin===id?'on':''}" data-origin="${id}">${l}</button>`).join('');document.querySelectorAll('[data-origin]').forEach(b=>b.onclick=()=>{flash(b);state.origin=b.dataset.origin;state.mesa=state.origin==='mesa'?(state.mesa||1):null;state.employee=state.origin==='personal'?(state.employee||APP.employees[0]):null;state.packagingManual=state.origin==='personal';state.packagingCount=0;state.discountAmount=0;state.category='Favoritos';$('search').value='';renderOrigin();renderTables();renderEmployees();renderCats();renderProducts();renderAccounts();renderCart()})}
function renderTables(){$('tables').innerHTML=state.origin==='mesa'?Array.from({length:12},(_,i)=>`<button class="${state.mesa===i+1?'on':''}" data-mesa="${i+1}">Mesa ${i+1}</button>`).join(''):'';document.querySelectorAll('[data-mesa]').forEach(b=>b.onclick=()=>{flash(b);state.mesa=Number(b.dataset.mesa);renderTables();renderCart()})}function renderEmployees(){$('employees').innerHTML=state.origin==='personal'?'<p class="mut" style="width:100%;margin:4px 0 0">Empleado:</p>'+APP.employees.map(n=>`<button class="${state.employee===n?'on':''}" data-emp="${n}">${n}</button>`).join(''):'';document.querySelectorAll('[data-emp]').forEach(b=>b.onclick=()=>{flash(b);state.employee=b.dataset.emp;renderEmployees();renderCart()})}
function renderAccounts(){$('accounts').innerHTML=Array.from({length:6},(_,i)=>`<button class="${state.account===i+1?'on':''}" data-acc="${i+1}">Cuenta ${i+1}</button>`).join('');document.querySelectorAll('[data-acc]').forEach(b=>b.onclick=()=>{flash(b);state.account=Number(b.dataset.acc);renderAccounts();renderCart()})}
const CATEGORY_ORDER=CONFIG.categoryOrder||[];
const CATEGORY_LABELS=CONFIG.categoryLabels||{};
function catLabel(c){return CATEGORY_LABELS[c]||c}
function categories(){const available=[...new Set(PRODUCTS.filter(avail).map(p=>p.category))];return ['Favoritos',...CATEGORY_ORDER.filter(c=>available.includes(c)),...available.filter(c=>!CATEGORY_ORDER.includes(c)).sort()]}function renderCats(){$('cats').innerHTML=categories().map(c=>`<button class="${state.category===c?'on':''}" data-cat="${c}">${catLabel(c)}</button>`).join('');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{flash(b);state.category=b.dataset.cat;$('search').value='';renderCats();renderProducts()})}
function renderProducts(){const q=$('search').value.trim().toLowerCase();let list=PRODUCTS.filter(avail);if(q){list=list.filter(p=>p.name.toLowerCase().includes(q)||p.category.toLowerCase().includes(q))}else if(state.category==='Favoritos'){list=list.filter(p=>fav.includes(p.id))}else{list=list.filter(p=>p.category===state.category)}list=list.slice().sort((a,b)=>a.name.localeCompare(b.name,'es',{sensitivity:'base'}));$('products').innerHTML=list.length?list.map(p=>`<button class="prod" data-prod="${p.id}">${p.name}<small>${catLabel(p.category)} · ${money(price(p))}</small></button>`).join(''):'<div class="empty">No hay productos con ese filtro.</div>';document.querySelectorAll('[data-prod]').forEach(b=>b.onclick=()=>{flash(b);openExtras(b.dataset.prod)})}
$('search').addEventListener('input',renderProducts);
function renderQuick(){$('quick').innerHTML=APP.quick.map(n=>`<button data-note="${n}">${n}</button>`).join('');document.querySelectorAll('[data-note]').forEach(b=>b.onclick=()=>{flash(b);$('notes').value=($('notes').value?$('notes').value+'; ':'')+b.dataset.note})}
function extrasFor(p){const c=p.category.toLowerCase();let list=[];if(c.includes('hamburguesas'))list=APP.extras.hamburguesa||[];else if(c.includes('ensaladas'))list=APP.extras.ensalada||[];else if(c.includes('huevos'))list=APP.extras.desayuno||[];else if(c.includes('waffles salados'))list=APP.extras.waffle||[];else if(c.includes('croissants')||c.includes('sándwiches')||c.includes('sandwiches')||c.includes('paninis'))list=APP.extras.comida||[];return [...list,['Extra',20]]}
function openExtras(id){state.target=PRODUCTS.find(p=>p.id===id);const list=extrasFor(state.target);$('extraTitle').textContent=state.target.name;$('extras').innerHTML=list.map(([n,p],i)=>`<label class="extra"><input type="checkbox" data-extra="${i}"><span>${n} +${money(p)}</span></label>`).join('');$('extraModal').dataset.kind=state.target.id;document.querySelectorAll('.extra').forEach(l=>l.onclick=()=>flash(l));$('extraModal').classList.add('on')}
$('extraCancel').onclick=()=>$('extraModal').classList.remove('on');$('extraAdd').onclick=()=>{const list=extrasFor(state.target);const extras=[...document.querySelectorAll('[data-extra]:checked')].map(x=>{const e=list[Number(x.dataset.extra)];return{name:e[0],price:e[1]}});addProduct(state.target,extras);$('extraModal').classList.remove('on')};
function addProduct(p,extras){const acc=state.account||1;const key=p.id+'|'+acc+'|'+extras.map(e=>e.name).join(',');const found=state.cart.find(i=>i.key===key);if(found)found.qty++;else state.cart.push({key,id:p.id,name:p.name,base:price(p),qty:1,extras,account:acc});renderCart()}
function currentLabel(){return state.origin==='mesa'?`🪑 Mesa ${state.mesa}`:(state.origin==='personal'?`👤 Personal · ${state.employee||'Sin nombre'}`:labels[state.origin])}function itemTotal(i){return (i.base+i.extras.reduce((a,e)=>a+e.price,0))*i.qty}function currentPackagingQty(){if(state.origin!=='llevar'&&state.origin!=='personal')return 0;if(state.packagingManual)return Math.max(0,Number(state.packagingCount||0));return state.origin==='llevar'?packagingQty(state.cart):0}function total(){let t=state.cart.reduce((a,i)=>a+itemTotal(i),0);t+=currentPackagingQty()*APP.packagingFee;t-=Number(state.discountAmount||0);return Math.max(0,t)}
function itemsByAccount(items){const g={};items.forEach(i=>{const a=i.account||1;(g[a]||(g[a]=[])).push(i)});return g}
function accountSubtotal(items,acc){return items.filter(i=>(i.account||1)===Number(acc)).reduce((a,i)=>a+itemTotal(i),0)}
function needsPackaging(item){return !APP.noPackaging.includes(item.id)}
function packagingQty(items){return (items||[]).filter(needsPackaging).reduce((a,i)=>a+(Number(i.qty)||0),0)}
function packagingTotal(items){return packagingQty(items)*APP.packagingFee}function orderPackagingQty(o){if(!o||!['llevar','personal'].includes(o.origin))return 0;if(o.packagingQty!==undefined&&o.packagingQty!==null)return Math.max(0,Number(o.packagingQty||0));return o.origin==='llevar'?packagingQty(o.items||[]):0}function orderPackagingTotal(o){return orderPackagingQty(o)*APP.packagingFee}
function groupedList(items){const g=itemsByAccount(items);return Object.keys(g).sort((a,b)=>a-b).map(acc=>`<div class="accountBlock"><h4>Cuenta ${acc} · ${money(accountSubtotal(items,acc))}</h4><ul>${g[acc].map(i=>`<li>${i.qty} × ${i.name}${i.extras.length?' ('+i.extras.map(e=>e.name).join(', ')+')':''}</li>`).join('')}</ul></div>`).join('')}
function renderCart(){
  $('meta').textContent=currentLabel();
  renderAccounts();
  let html='';
  if(!state.cart.length){
    html='<div class="empty">Agrega productos al pedido.</div>';
  }else{
    const g=itemsByAccount(state.cart);
    html=Object.keys(g).sort((a,b)=>a-b).map(acc=>`<div class="accountBlock"><h4>Cuenta ${acc} · ${money(accountSubtotal(state.cart,acc))}</h4>${g[acc].map(i=>{const idx=state.cart.indexOf(i);return `<div class="item"><b>${i.qty} × ${i.name}</b><small>${i.extras.length?i.extras.map(e=>e.name).join(', ')+' · ':''}${money(itemTotal(i))}</small><div class="ctrl"><button data-plus="${idx}">+</button><button data-minus="${idx}">−</button><button data-del="${idx}">Eliminar</button><button data-move="${idx}">Cambiar cuenta</button></div></div>`}).join('')}</div>`).join('');
  }
  if(state.origin==='llevar'||state.origin==='personal'){
    const q=currentPackagingQty();
    html+=`<div class="item packagingControl"><b>Envases</b><small>${money(q*APP.packagingFee)}</small><div class="ctrl"><button id="packMinus">−</button><span class="pill">${q}</span><button id="packPlus">+</button>${state.origin==='llevar'&&state.packagingManual?'<button id="packAuto">Automático</button>':''}</div></div>`;
  }
  if(state.origin==='didi'||state.origin==='uber'){
    const d=Math.max(0,Number(state.discountAmount||0));
    html+=`<div class="item discountControl"><b>Descuento temporal</b><small>−${money(d)}</small><div class="ctrl"><button id="discMinus10">− $10</button><button id="discMinus1">− $1</button><span class="pill">${money(d)}</span><button id="discPlus1">+ $1</button><button id="discPlus10">+ $10</button><button id="discReset">Limpiar</button></div></div>`;
  }
  $('cart').innerHTML=html;
  document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>{flash(b);state.cart[Number(b.dataset.plus)].qty++;renderCart()});
  document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>{flash(b);const i=Number(b.dataset.minus);state.cart[i].qty--;if(state.cart[i].qty<1)state.cart.splice(i,1);renderCart()});
  document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{flash(b);state.cart.splice(Number(b.dataset.del),1);renderCart()});
  document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{flash(b);const i=Number(b.dataset.move);const n=Number(prompt('Mover a cuenta (1-6):',state.cart[i].account||1));if(n>=1&&n<=6){state.cart[i].account=n;state.cart[i].key=state.cart[i].id+'|'+n+'|'+state.cart[i].extras.map(e=>e.name).join(',');renderCart()}});
  if($('packMinus'))$('packMinus').onclick=()=>{flash($('packMinus'));if(!state.packagingManual){state.packagingCount=currentPackagingQty();state.packagingManual=true}state.packagingCount=Math.max(0,Number(state.packagingCount||0)-1);renderCart()};
  if($('packPlus'))$('packPlus').onclick=()=>{flash($('packPlus'));if(!state.packagingManual){state.packagingCount=currentPackagingQty();state.packagingManual=true}state.packagingCount=Number(state.packagingCount||0)+1;renderCart()};
  if($('packAuto'))$('packAuto').onclick=()=>{flash($('packAuto'));state.packagingManual=false;state.packagingCount=0;renderCart()};
  const setDiscount=delta=>{state.discountAmount=Math.max(0,Number(state.discountAmount||0)+delta);renderCart()};
  if($('discMinus10'))$('discMinus10').onclick=()=>setDiscount(-10);
  if($('discMinus1'))$('discMinus1').onclick=()=>setDiscount(-1);
  if($('discPlus1'))$('discPlus1').onclick=()=>setDiscount(1);
  if($('discPlus10'))$('discPlus10').onclick=()=>setDiscount(10);
  if($('discReset'))$('discReset').onclick=()=>{state.discountAmount=0;renderCart()};
  $('total').textContent=money(total())
}
$('clear').onclick=()=>{flash($('clear'));state.cart=[];state.editId=null;state.editArchiveId=null;state.account=1;state.packagingManual=state.origin==='personal';state.packagingCount=0;state.discountAmount=0;$('notes').value='';renderAccounts();renderCart();$('send').textContent='Enviar pedido'};$('send').onclick=()=>{flash($('send'));if(!state.cart.length){alert('Agrega al menos un producto.');return}if(state.origin==='personal'&&!state.employee){alert('Selecciona quién del personal está pidiendo.');return}const payload={origin:state.origin,mesa:state.mesa,employee:state.employee,items:JSON.parse(JSON.stringify(state.cart)),packagingQty:currentPackagingQty(),discountAmount:Math.max(0,Number(state.discountAmount||0)),notes:$('notes').value,total:total()};if(state.editArchiveId&&state.editId){const a=(state.archives||[]).find(x=>x.id===state.editArchiveId);const o=a&&(a.orders||[]).find(x=>x.id===state.editId);if(o){Object.assign(o,payload);o.adminEdited=true;o.adminEditedAt=Date.now();o.adminEditNote='Editado por administrador después del cierre';a.inventory=recomputeArchiveInventory(a);a.summary=buildSummary(a.orders||[],'Corte guardado',null);a.updatedAt=new Date().toISOString();}const archiveId=state.editArchiveId;state.editId=null;state.editArchiveId=null;$('send').textContent='Enviar pedido';state.cart=[];state.account=1;state.packagingManual=state.origin==='personal';state.packagingCount=0;state.discountAmount=0;$('notes').value='';save();init();show('screenArchives','tabClose');renderArchiveDetail(archiveId);return}else if(state.editId){const o=state.orders.find(x=>x.id===state.editId);Object.assign(o,payload);state.editId=null;$('send').textContent='Enviar pedido';}else{state.orders.unshift({id:state.seq++,created:Date.now(),status:'Pendiente',...payload});}state.cart=[];state.account=1;state.packagingManual=state.origin==='personal';state.packagingCount=0;state.discountAmount=0;$('notes').value='';save();init();show('screenActive','tabActive')};
function orderPlace(o){return o.origin==='mesa'?'🪑 Mesa '+o.mesa:(o.origin==='personal'?'👤 Personal · '+(o.employee||'Sin nombre'):labels[o.origin])}function minutes(t){return Math.max(0,Math.floor((Date.now()-t)/60000))}function renderOrders(){const active=state.orders.filter(o=>o.status!=='Entregado'&&!isError(o));$('orders').innerHTML=active.length?active.map(o=>`<div class="order"><h3>#${String(o.id).padStart(3,'0')} · ${orderPlace(o)}</h3><span class="pill">${o.status}</span> <span class="pill">${minutes(o.created)} min</span> <span class="pill">${money(o.total)}</span>${groupedList(o.items)}${orderPackagingQty(o)>0?`<ul><li>Envase x${orderPackagingQty(o)} (${money(orderPackagingTotal(o))})</li></ul>`:''}${Number(o.discountAmount||0)>0?`<ul><li>Descuento: −${money(o.discountAmount)}</li></ul>`:''}${o.notes?`<p>${o.notes}</p>`:''}<button data-edit="${o.id}">Editar</button><button class="danger" data-error="${o.id}">Marcar error</button><button class="next" data-next="${o.id}">${o.status} →</button></div>`).join(''):'<div class="empty">Sin pedidos activos.</div>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editOrder(Number(b.dataset.edit)));document.querySelectorAll('[data-error]').forEach(b=>b.onclick=()=>markOrderError(Number(b.dataset.error)));document.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>{const o=state.orders.find(x=>x.id===Number(b.dataset.next));o.status={Pendiente:'Preparando',Preparando:'Listo',Listo:'Entregado'}[o.status]||'Entregado';save();renderOrders();renderSummary()})}
function buildSummary(orders,title,seqText){const valid=validOrders(orders);const errors=(orders||[]).filter(isError);const groups={mesa:[],llevar:[],didi:[],uber:[],personal:[]};valid.forEach(o=>(groups[o.origin]||(groups[o.origin]=[])).push(o));let grand=0,txt=`Gold 71 Café · Galaxia OS\n${title}\n\n`;APP.origins.forEach(([id,l])=>{const sum=(groups[id]||[]).reduce((a,o)=>a+o.total,0);grand+=sum;txt+=`${l}: ${(groups[id]||[]).length} pedidos · ${money(sum)}\n`});txt+=`\nTOTAL VENTAS: ${money(grand)}\nErrores de pedido: ${errors.length}`;if(errors.length){const lost=errors.reduce((a,o)=>a+(o.total||0),0);txt+=` · Monto no cobrado: ${money(lost)}`}if(seqText)txt+=`\n${seqText}`;return txt}
function productCounts(orders){const counts={};validOrders(orders).forEach(o=>o.items.forEach(i=>{const name=i.name+(i.extras&&i.extras.length?' ('+i.extras.map(e=>e.name).join(', ')+')':'');counts[name]=(counts[name]||0)+i.qty}));return Object.entries(counts).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))}
function renderProductCounts(orders){const counts=productCounts(orders);return counts.length?`<div class="accountBlock"><h4>Productos vendidos</h4><ul>${counts.map(([n,q])=>`<li>${q} × ${n}</li>`).join('')}</ul></div>`:''}

function renderErrors(orders){const errors=(orders||[]).filter(isError);return errors.length?`<div class="accountBlock errorBlock"><h4>⚠ Errores de pedido (${errors.length})</h4>${errors.map(o=>`<div class="errorRow"><b>#${String(o.id).padStart(3,'0')} · ${orderPlace(o)} · ${money(o.total)}</b><br><small>${o.errorReason||'Sin motivo'} · ${o.errorEmployee||'Sin responsable'} · ${new Date(o.errorAt||o.created).toLocaleString()}</small>${groupedList(o.items)}</div>`).join('')}</div>`:''}
function ensureErrorModal(){let m=$('errorModal');if(m)return m;m=document.createElement('div');m.id='errorModal';m.className='modalBack';m.innerHTML=`<div class="modal"><h2>⚠ Marcar error de pedido</h2><p class="mut" id="errorModalOrder"></p><h3>¿Quién cometió o registró el error?</h3><div id="errorEmployeeChoices" class="choiceGrid"></div><h3>Motivo</h3><div id="errorReasonChoices" class="choiceGrid"></div><p class="mut">El pedido no se borrará. Quedará guardado como error y no sumará en ventas ni productos vendidos.</p><div class="row"><button id="errorCancel">Cancelar</button><button id="errorConfirm" class="danger">Marcar como error</button></div></div>`;document.body.appendChild(m);return m}
function markOrderError(id){const o=state.orders.find(x=>x.id===id);if(!o)return;const m=ensureErrorModal();const reasons=['Cliente canceló','Se tomó mal la orden','Producto equivocado','Pedido duplicado','Error de captura','Error de cocina','Otro'];let employee='';let reason='';$('errorModalOrder').textContent=`Pedido #${String(o.id).padStart(3,'0')} · ${orderPlace(o)} · ${money(o.total)}`;$('errorEmployeeChoices').innerHTML=APP.employees.map(n=>`<button data-error-emp="${n}">${n}</button>`).join('');$('errorReasonChoices').innerHTML=reasons.map(n=>`<button data-error-reason="${n}">${n}</button>`).join('');const update=()=>{$('errorConfirm').disabled=!(employee&&reason);document.querySelectorAll('[data-error-emp]').forEach(b=>b.classList.toggle('on',b.dataset.errorEmp===employee));document.querySelectorAll('[data-error-reason]').forEach(b=>b.classList.toggle('on',b.dataset.errorReason===reason))};document.querySelectorAll('[data-error-emp]').forEach(b=>b.onclick=()=>{flash(b);employee=b.dataset.errorEmp;update()});document.querySelectorAll('[data-error-reason]').forEach(b=>b.onclick=()=>{flash(b);reason=b.dataset.errorReason;update()});$('errorCancel').onclick=()=>m.classList.remove('on');$('errorConfirm').onclick=()=>{if(!(employee&&reason))return;o.status='Error de pedido';o.errorReason=reason;o.errorEmployee=employee;o.errorAt=Date.now();save();m.classList.remove('on');renderOrders();renderSummary();renderArchives()};update();m.classList.add('on')}


function renderSummary(){$('summary').textContent=buildSummary(state.orders,'Corte del día',`Siguiente pedido: #${String(state.seq).padStart(3,'0')}`);$('history').innerHTML=renderProductCounts(state.orders)+renderErrors(state.orders)+state.orders.map(o=>`<div class="historyItem ${isError(o)?'orderError':''}"><b>#${String(o.id).padStart(3,'0')} · ${orderPlace(o)} · ${money(o.total)}</b><br><small>${new Date(o.created).toLocaleTimeString()} · ${o.status}${isError(o)?' · '+(o.errorReason||'Sin motivo')+' · '+(o.errorEmployee||'Sin responsable'):''}</small>${groupedList(o.items)}${orderPackagingQty(o)>0?`<ul><li>Envase x${orderPackagingQty(o)} (${money(orderPackagingTotal(o))})</li></ul>`:''}${Number(o.discountAmount||0)>0?`<ul><li>Descuento: −${money(o.discountAmount)}</li></ul>`:''}${o.notes?`<p>${o.notes}</p>`:''}${!isError(o)?`<button data-edit="${o.id}">Editar</button><button class="danger" data-error="${o.id}">Marcar error</button>`:''}</div>`).join('');document.querySelectorAll('#history [data-edit]').forEach(b=>b.onclick=()=>editOrder(Number(b.dataset.edit)));document.querySelectorAll('#history [data-error]').forEach(b=>b.onclick=()=>markOrderError(Number(b.dataset.error)))}

function editOrder(id,archiveId){let o=null;if(archiveId){const a=(state.archives||[]).find(x=>x.id===archiveId);o=a&&(a.orders||[]).find(x=>x.id===id);state.editArchiveId=archiveId}else{o=state.orders.find(x=>x.id===id);state.editArchiveId=null}if(!o)return;if(isError(o)&&!archiveId){alert('Este pedido está marcado como error y no se puede editar.');return;}state.editId=id;state.origin=o.origin;state.mesa=o.mesa||null;state.employee=o.employee||null;state.cart=JSON.parse(JSON.stringify(o.items)).map(i=>({...i,account:i.account||1,key:i.key||i.id+'|'+(i.account||1)+'|'+(i.extras||[]).map(e=>e.name).join(',')}));state.account=1;state.packagingManual=true;state.packagingCount=orderPackagingQty(o);state.discountAmount=Math.max(0,Number(o.discountAmount||0));$('notes').value=o.notes||'';state.category='Favoritos';$('search').value='';$('send').textContent=archiveId?'Guardar corrección':'Guardar cambios';renderOrigin();renderTables();renderEmployees();renderCats();renderProducts();renderCart();show('screenNew','tabNew')}
function ownerPass(){const p=prompt('Contraseña de administración:');return p===OWNER_PASSWORD}
function closeDay(){if(!state.orders.length){alert('No hay pedidos para cerrar.');return}if(!confirm('Se guardará el corte de hoy en Historial de cierres y se limpiará la pantalla para empezar de nuevo en #001. ¿Cerrar día?'))return;const now=new Date();const archive={id:Date.now(),closedAt:now.toISOString(),label:now.toLocaleDateString(),orders:JSON.parse(JSON.stringify(state.orders)),summary:buildSummary(state.orders,'Corte guardado',null)};state.archives.unshift(archive);state.orders=[];state.seq=1;save();renderOrders();renderSummary();renderArchives();$('next').textContent='#001';alert('Corte guardado. Ya puedes iniciar el nuevo día desde #001.')}
function renderArchives(){if(!$('archives'))return;const list=state.archives||[];$('archives').innerHTML=list.length?list.map(a=>`<div class="historyItem"><div class="row between"><div><b>${new Date(a.closedAt).toLocaleDateString()} · ${a.orders.length} pedidos</b><br><small>Cerrado: ${new Date(a.closedAt).toLocaleString()}</small></div><button class="danger" data-del-archive="${a.id}">Borrar respaldo</button></div><pre>${buildSummary(a.orders,'Corte guardado',null)}</pre>${renderProductCounts(a.orders)}${renderErrors(a.orders)}${a.orders.map(o=>`<div class="accountBlock ${isError(o)?'orderError':''}"><h4>#${String(o.id).padStart(3,'0')} · ${orderPlace(o)} · ${money(o.total)}</h4><small>${new Date(o.created).toLocaleTimeString()} · ${o.status}${isError(o)?' · '+(o.errorReason||'Sin motivo')+' · '+(o.errorEmployee||'Sin responsable'):''}</small>${groupedList(o.items)}${orderPackagingQty(o)>0?`<ul><li>Envase x${orderPackagingQty(o)} (${money(orderPackagingTotal(o))})</li></ul>`:''}${Number(o.discountAmount||0)>0?`<ul><li>Descuento: −${money(o.discountAmount)}</li></ul>`:''}${o.notes?`<p>${o.notes}</p>`:''}</div>`).join('')}</div>`).join(''):'<div class="empty">No hay cortes guardados.</div>';document.querySelectorAll('[data-del-archive]').forEach(b=>b.onclick=()=>deleteArchive(Number(b.dataset.delArchive)))}
function deleteArchive(id){if(!ownerPass())return;if(!confirm('Esto sí borra definitivamente este respaldo. ¿Seguro?'))return;state.archives=(state.archives||[]).filter(a=>a.id!==id);save();renderArchives()}

// === v5.0 Modular, administración, inventario y corrección de cierres ===
const INV_ITEMS=(window.GOLD71_INVENTORY&&window.GOLD71_INVENTORY.items)||[];
const INVENTORY_RESET_MARKER='g71_inventory_reset_v6';
function zeroInventory(){
  const empty={};
  INV_ITEMS.forEach(([id])=>empty[id]={initial:0,purchase:0,final:0});
  setInventory(empty);
  return empty;
}
function runV6InventoryReset(){
  if(localStorage.getItem(INVENTORY_RESET_MARKER)==='1')return;
  zeroInventory();
  localStorage.setItem(INVENTORY_RESET_MARKER,'1');
}
function getInventory(){const raw=JSON.parse(localStorage.getItem('g71_inventory')||'{}');INV_ITEMS.forEach(([id])=>{if(!raw[id])raw[id]={initial:0,purchase:0,final:null}});return raw}
function setInventory(inv){localStorage.setItem('g71_inventory',JSON.stringify(inv))}
function use(inv,id,qty){inv[id]=(inv[id]||0)+qty}
function isHamb(id){return id&&id.startsWith('hamb-')}
function isSandwich(id){return ['sandwich-gourmet','sandwich-grill','sandwich-club','sandwich-atun','club-monster'].includes(id)}
function isPanini(id){return id&&id.startsWith('panini-')}
function isWaffle(id){return id&&id.startsWith('waffle-')}
function isCroissant(id){return id&&id.startsWith('croissant-')}
function inventoryUsage(orders){const out={};validOrders(orders).forEach(o=>(o.items||[]).forEach(i=>{const id=i.id, q=Number(i.qty||0); if(!q)return;
  if(isHamb(id)){use(out,'hamburguesas',(id==='hamb-monster-doble'?2:id==='hamb-monster-triple'?3:1)*q);use(out,'bollos',q)}
  if(['bolognesa','sandwich-grill','panini-mediterraneo'].includes(id))use(out,'hamburguesas',q);
  if(['papas-monster','ensalada-suprema-arrachera','panini-ranch-arrachera'].includes(id))use(out,'arrachera',q);
  if(['ensalada-hawaiana','ensalada-cesar','croissant-chicken','sandwich-gourmet','club-monster','fetuccini','panini-turco','panini-hawaiano'].includes(id))use(out,'pechuga',q);
  if(isSandwich(id))use(out,'panCaja',q);
  if(isWaffle(id))use(out,'waffles',(id==='waffle-club'||id==='waffle-gold'?2:1)*q);
  if(isPanini(id))use(out,'paniniInv',q);
  if(['bolognesa','fetuccini'].includes(id))use(out,'pastasInv',q);
  if(['croissant-atun','sandwich-atun'].includes(id))use(out,'atunInv',q);
  if(isCroissant(id)||['cuernito-cajeta','cuernito-nutella'].includes(id))use(out,'cuernitos',q);
  if(['refresco','coca-zero'].includes(id))use(out,'refrescosInv',q);
  if(id==='agua-bonafont')use(out,'bonafontInv',q);
  if(id==='fuze-tea')use(out,'fuzeTeaInv',q);
  if(id==='frappe-ferrero')use(out,'ferreroInv',q);
  (i.extras||[]).forEach(e=>{if(e.name==='Arrachera')use(out,'arrachera',q); if(e.name==='Pollo')use(out,'pechuga',q)});
}));return out}
function buildInventorySnapshot(orders, pending=false){const inv=getInventory(), sold=inventoryUsage(orders), rows={};INV_ITEMS.forEach(([id,name])=>{const r=inv[id]||{initial:0,purchase:0,final:null};const initial=Number(r.initial||0), purchase=Number(r.purchase||0), vendido=Number(sold[id]||0), esperado=initial+purchase-vendido;const final=pending?null:((r.final===null||r.final===undefined)?esperado:Number(r.final||0));rows[id]={name,initial,purchase,vendido,esperado,final,diff:final===null||final===undefined?null:final-esperado}});return rows}

function recomputeArchiveInventory(archive){
  const previous=archive.inventory||{};
  const sold=inventoryUsage(archive.orders||[]);
  const rows={};
  const pending=archive.inventoryStatus==='pending';
  INV_ITEMS.forEach(([id,name])=>{
    const old=previous[id]||{};
    const initial=Number(old.initial||0);
    const purchase=Number(old.purchase||0);
    const vendido=Number(sold[id]||0);
    const esperado=initial+purchase-vendido;
    const final=(old.final===null||old.final===undefined)?(pending?null:esperado):Number(old.final||0);
    rows[id]={name,initial,purchase,vendido,esperado,final,diff:final===null||final===undefined?null:final-esperado};
  });
  return rows;
}
function carryInventoryForward(snapshot){const next={};INV_ITEMS.forEach(([id])=>{const row=snapshot[id];const start=row?Number((row.final===null||row.final===undefined)?row.esperado:row.final):0;next[id]={initial:start,purchase:0,final:start}});setInventory(next)}
function carryInventoryExpectedForward(snapshot){const next={};INV_ITEMS.forEach(([id])=>{const row=snapshot[id];const start=row?Number(row.esperado||0):0;next[id]={initial:start,purchase:0,final:start}});setInventory(next)}
function isInventoryPending(a){return a&&a.inventoryStatus==='pending'}
function originSums(orders){const valid=validOrders(orders), groups={mesa:0,llevar:0,didi:0,uber:0,personal:0};valid.forEach(o=>groups[o.origin]=(groups[o.origin]||0)+Number(o.total||0));groups.total=Object.values(groups).reduce((a,b)=>a+b,0);groups.count=valid.length;groups.errors=(orders||[]).filter(isError).length;return groups}
function archiveCard(a){const g=originSums(a.orders||[]);const pending=isInventoryPending(a);return `<div class="archiveCard ${pending?'pendingInventory':''}"><div class="row between"><div><h3>📅 ${new Date(a.closedAt).toLocaleDateString()}</h3><small>Cerrado: ${new Date(a.closedAt).toLocaleString()}</small><br><small>${pending?'🟡 Inventario pendiente':'🟢 Inventario confirmado'}</small></div><button data-archive-detail="${a.id}">Ver detalles</button></div><div class="archiveGrid"><div class="archiveStat"><small>Total</small><b>${money(g.total)}</b></div><div class="archiveStat"><small>🛵 Uber</small><b>${money(g.uber)}</b></div><div class="archiveStat"><small>🛵 DiDi</small><b>${money(g.didi)}</b></div><div class="archiveStat"><small>🪑 Mesas</small><b>${money(g.mesa)}</b></div><div class="archiveStat"><small>🥡 Para llevar</small><b>${money(g.llevar)}</b></div><div class="archiveStat"><small>👤 Personal</small><b>${money(g.personal)}</b></div><div class="archiveStat"><small>Pedidos</small><b>${g.count}</b></div><div class="archiveStat"><small>Errores</small><b>${g.errors}</b></div></div></div>`}
function renderAdminHome(){if(!$('screenArchives'))return;$('screenArchives').innerHTML=`<div class="panel"><div class="row between"><h2>🔐 Administración</h2><button id="backClose">Volver al corte</button></div><p class="mut">Sección protegida para cierres, inventario y gráficas.</p><div class="adminMenu"><button id="adminHistory">📊 Historial de cierres</button><button id="adminInventory">📦 Inventario</button><button id="adminCharts">📈 Gráficas</button></div></div>`;$('backClose').onclick=()=>show('screenClose','tabClose');$('adminHistory').onclick=renderArchiveCards;$('adminInventory').onclick=renderInventory;$('adminCharts').onclick=renderChartsHome}

function allStoredOrders(){
  const out=[];
  (state.orders||[]).forEach(o=>out.push(o));
  (state.archives||[]).forEach(a=>(a.orders||[]).forEach(o=>out.push({...o,closedAt:a.closedAt})));
  return out;
}
function periodStart(period){
  const now=new Date();
  if(period==='all')return 0;
  const d=new Date(now);
  if(period==='today'){d.setHours(0,0,0,0);return d.getTime()}
  if(period==='week'){const day=d.getDay()||7;d.setHours(0,0,0,0);d.setDate(d.getDate()-day+1);return d.getTime()}
  if(period==='month'){d.setDate(1);d.setHours(0,0,0,0);return d.getTime()}
  return 0;
}
function ordersForChart(period){const start=periodStart(period);return validOrders(allStoredOrders()).filter(o=>Number(o.created||0)>=start)}
function periodLabel(p){return p==='today'?'Hoy':p==='week'?'Esta semana':p==='month'?'Este mes':'Todo el historial'}
function renderChartControls(type,period,metric){
  const periods=[['today','Hoy'],['week','Semana'],['month','Mes'],['all','Todo']];
  return `<div class="chartControls">${periods.map(([id,l])=>`<button class="${period===id?'on':''}" data-chart-period="${id}">${l}</button>`).join('')}</div>`+
  (type==='top'?`<div class="chartControls"><button class="${metric==='qty'?'on':''}" data-chart-metric="qty">Cantidad vendida</button><button class="${metric==='revenue'?'on':''}" data-chart-metric="revenue">Ingreso generado</button></div>`:'');
}
function productTopData(orders,metric){
  const map={};
  orders.forEach(o=>(o.items||[]).forEach(i=>{
    if(!map[i.name])map[i.name]={name:i.name,qty:0,revenue:0};
    map[i.name].qty+=Number(i.qty||0);
    map[i.name].revenue+=itemTotal(i);
  }));
  return Object.values(map).sort((a,b)=>(metric==='revenue'?b.revenue-a.revenue:b.qty-a.qty)).slice(0,15);
}
function renderTopProductsChart(period='today',metric='qty'){
  const orders=ordersForChart(period), data=productTopData(orders,metric), max=Math.max(1,...data.map(d=>metric==='revenue'?d.revenue:d.qty));
  $('screenArchives').innerHTML=`<div class="panel"><div class="row between"><h2>🏆 Top productos vendidos</h2><button id="chartsBack">Volver</button></div>${renderChartControls('top',period,metric)}<div class="chartBox"><h3>${metric==='revenue'?'Ingreso generado':'Cantidad vendida'} · ${periodLabel(period)}</h3>${data.length?data.map(d=>{const v=metric==='revenue'?d.revenue:d.qty;return `<div class="barRow"><div class="barLabel">${d.name}</div><div class="barTrack"><div class="barFill" style="width:${Math.max(2,(v/max)*100)}%"></div></div><div class="barValue">${metric==='revenue'?money(v):v}</div></div>`}).join(''):'<div class="empty">No hay ventas en este periodo.</div>'}</div></div>`;
  $('chartsBack').onclick=renderChartsHome;
  document.querySelectorAll('[data-chart-period]').forEach(b=>b.onclick=()=>renderTopProductsChart(b.dataset.chartPeriod,metric));
  document.querySelectorAll('[data-chart-metric]').forEach(b=>b.onclick=()=>renderTopProductsChart(period,b.dataset.chartMetric));
}
function originChartData(orders){const labelsMap=Object.fromEntries(APP.origins||[]);const rows=(APP.origins||[]).map(([id,l])=>({id,label:l,total:0,count:0}));orders.forEach(o=>{const r=rows.find(x=>x.id===o.origin);if(r){r.total+=Number(o.total||0);r.count++}});return rows.filter(r=>r.total>0||r.count>0)}
function renderOriginChart(period='today', selected=null){
  const rows=originChartData(ordersForChart(period));
  const total=rows.reduce((a,r)=>a+r.total,0);
  const colorFor=id=>ORIGIN_COLORS[id]||'#d4af37';
  let acc=0;
  const stops=rows.map(r=>{const start=total?acc/total*100:0;acc+=r.total;const end=total?acc/total*100:0;return `${colorFor(r.id)} ${start}% ${end}%`;}).join(',')||'#222 0 100%';
  const selectedRow=rows.find(r=>r.id===selected)||rows[0]||null;
  const detail=selectedRow?`<div class="originDetail" style="border-color:${colorFor(selectedRow.id)}"><h3>${selectedRow.label}</h3><div class="archiveGrid"><div class="archiveStat"><small>Ventas</small><b>${money(selectedRow.total)}</b></div><div class="archiveStat"><small>Pedidos</small><b>${selectedRow.count}</b></div><div class="archiveStat"><small>Ticket promedio</small><b>${money(selectedRow.count?selectedRow.total/selectedRow.count:0)}</b></div><div class="archiveStat"><small>Porcentaje</small><b>${total?Math.round(selectedRow.total/total*100):0}%</b></div></div></div>`:'';
  $('screenArchives').innerHTML=`<div class="panel"><div class="row between"><h2>🍩 Ventas por origen</h2><button id="chartsBack">Volver</button></div>${renderChartControls('origin',period,'revenue')}<div class="chartBox"><div class="donutWrap"><div class="donut" style="background:conic-gradient(${stops})"><div class="donutCenter"><span>${money(total)}</span><small>${periodLabel(period)}</small></div></div><div class="chartLegend">${rows.length?rows.map(r=>`<button class="legendItem legendButton ${selectedRow&&selectedRow.id===r.id?'selected':''}" data-origin-chart="${r.id}" style="border-color:${selectedRow&&selectedRow.id===r.id?colorFor(r.id):'#282828'}"><b><span class="sliceDot" style="background:${colorFor(r.id)}"></span>${r.label}</b><br><small>${r.count} pedidos · ${total?Math.round(r.total/total*100):0}%</small><br><strong>${money(r.total)}</strong><br><small>Ticket prom.: ${money(r.count?r.total/r.count:0)}</small></button>`).join(''):'<div class="empty">No hay ventas en este periodo.</div>'}</div></div>${detail}</div></div>`;
  $('chartsBack').onclick=renderChartsHome;
  document.querySelectorAll('[data-chart-period]').forEach(b=>b.onclick=()=>renderOriginChart(b.dataset.chartPeriod,selected));
  document.querySelectorAll('[data-origin-chart]').forEach(b=>b.onclick=()=>renderOriginChart(period,b.dataset.originChart));
}
function renderChartsHome(){
  $('screenArchives').innerHTML=`<div class="panel"><div class="row between"><h2>📈 Gráficas</h2><button id="adminBack">Volver</button></div><p class="mut">Consulta ventas acumuladas de pedidos actuales y cierres guardados.</p><div class="adminMenu"><button id="chartTop">🏆 Top productos vendidos</button><button id="chartOrigin">🍩 Ventas por origen</button></div></div>`;
  $('adminBack').onclick=renderAdminHome;
  $('chartTop').onclick=()=>renderTopProductsChart('today','qty');
  $('chartOrigin').onclick=()=>renderOriginChart('today');
}

function renderArchiveCards(){const list=(state.archives||[]).slice().sort((a,b)=>(isInventoryPending(b)?1:0)-(isInventoryPending(a)?1:0)||Number(b.id||0)-Number(a.id||0));$('screenArchives').innerHTML=`<div class="panel"><div class="row between"><h2>📊 Historial de cierres</h2><button id="adminBack">Volver</button></div>${list.length?list.map(archiveCard).join(''):'<div class="empty">No hay cortes guardados.</div>'}</div>`;$('adminBack').onclick=renderAdminHome;document.querySelectorAll('[data-archive-detail]').forEach(b=>b.onclick=()=>renderArchiveDetail(Number(b.dataset.archiveDetail)))}
function inventoryTableFromSnapshot(snapshot){if(!snapshot)return '';return `<div class="accountBlock"><h4>📦 Inventario del cierre</h4><div class="inventoryWrap"><table class="inventoryTable"><thead><tr><th>Producto</th><th>Inicial</th><th>Compra</th><th>Vendido</th><th>Esperado</th><th>Final</th><th>Dif.</th></tr></thead><tbody>${INV_ITEMS.map(([id,name])=>{const r=snapshot[id]||{};const pending=r.final===null||r.final===undefined;const d=pending?null:Number(r.diff||0);return `<tr><td>${name}</td><td>${r.initial||0}</td><td>${r.purchase||0}</td><td>${r.vendido||0}</td><td>${r.esperado||0}</td><td>${pending?'Pendiente':r.final||0}</td><td class="${pending?'':d<0?'diffNeg':d>0?'diffPos':'diffZero'}">${pending?'—':d}</td></tr>`}).join('')}</tbody></table></div></div>`}
function archiveOrderCard(a,o){return `<div class="accountBlock ${isError(o)?'orderError':''}"><h4>#${String(o.id).padStart(3,'0')} · ${orderPlace(o)} · ${money(o.total)}</h4><small>${new Date(o.created).toLocaleTimeString()} · ${o.status}${isError(o)?' · '+(o.errorReason||'Sin motivo')+' · '+(o.errorEmployee||'Sin responsable'):''}${o.adminEdited?' · Editado por administrador':''}</small>${groupedList(o.items)}${orderPackagingQty(o)>0?`<ul><li>Envase x${orderPackagingQty(o)} (${money(orderPackagingTotal(o))})</li></ul>`:''}${Number(o.discountAmount||0)>0?`<ul><li>Descuento: −${money(o.discountAmount)}</li></ul>`:''}${o.notes?`<p>${o.notes}</p>`:''}${o.adminEdited?`<p class="mut">${o.adminEditNote||'Editado después del cierre'}${o.adminEditedAt?' · '+new Date(o.adminEditedAt).toLocaleString():''}</p>`:''}<button class="adminEdit" data-archive-edit="${a.id}|${o.id}">✏️ Corregir pedido cerrado</button></div>`}
function pendingInventoryEditor(a){if(!a.inventory)a.inventory=buildInventorySnapshot(a.orders||[],true);return `<div class="accountBlock pendingBlock"><h4>🟡 Inventario pendiente de confirmar</h4><p class="mut">Este cierre ya guardó ventas y pedidos. Captura el inventario final real cuando lo revises y presiona Confirmar inventario.</p><div class="inventoryWrap"><table class="inventoryTable"><thead><tr><th>Producto</th><th>Inicial</th><th>Compra</th><th>Vendido</th><th>Esperado</th><th>Final real</th><th>Dif.</th></tr></thead><tbody>${INV_ITEMS.map(([id,name])=>{const r=a.inventory[id]||{};const esperado=Number(r.esperado||0);const final=(r.final===null||r.final===undefined)?esperado:Number(r.final||0);const diff=final-esperado;return `<tr><td>${name}</td><td>${r.initial||0}</td><td>${r.purchase||0}</td><td>${r.vendido||0}</td><td>${esperado}</td><td><div class="stepper"><button data-archive-inv="${a.id}" data-inv-id="${id}" data-delta="-1" data-base="${final}">−</button><span>${final}</span><button data-archive-inv="${a.id}" data-inv-id="${id}" data-delta="1" data-base="${final}">+</button></div></td><td class="${diff<0?'diffNeg':diff>0?'diffPos':'diffZero'}">${diff}</td></tr>`}).join('')}</tbody></table></div><button id="confirmArchiveInventory">Confirmar inventario</button></div>`}
function adjustArchiveInventory(archiveId,itemId,delta,base){const a=(state.archives||[]).find(x=>x.id===archiveId);if(!a)return;if(!a.inventory)a.inventory=buildInventorySnapshot(a.orders||[],true);const r=a.inventory[itemId];if(!r)return;const current=(r.final===null||r.final===undefined)?Number(base||r.esperado||0):Number(r.final||0);r.final=Math.max(0,current+delta);r.diff=r.final-Number(r.esperado||0);a.inventoryStatus='pending';save();renderArchiveDetail(archiveId)}
function confirmArchiveInventory(archiveId){const a=(state.archives||[]).find(x=>x.id===archiveId);if(!a)return;if(!a.inventory)a.inventory=buildInventorySnapshot(a.orders||[],true);INV_ITEMS.forEach(([id])=>{const r=a.inventory[id];if(!r)return;if(r.final===null||r.final===undefined)r.final=Number(r.esperado||0);r.diff=Number(r.final||0)-Number(r.esperado||0)});a.inventoryStatus='confirmed';a.inventoryConfirmedAt=new Date().toISOString();carryInventoryForward(a.inventory);save();alert('Inventario confirmado y guardado en el cierre. También quedó como inventario inicial del día actual.');renderArchiveDetail(archiveId)}
function renderArchiveDetail(id){const a=(state.archives||[]).find(x=>x.id===id);if(!a)return;const g=originSums(a.orders||[]);const invSection=isInventoryPending(a)?pendingInventoryEditor(a):inventoryTableFromSnapshot(a.inventory);$('screenArchives').innerHTML=`<div class="panel"><div class="row between"><h2>📅 ${new Date(a.closedAt).toLocaleDateString()}</h2><div class="row"><button id="archiveBack">Volver</button><button class="danger" data-del-archive="${a.id}">Borrar respaldo</button></div></div><p class="mut">${isInventoryPending(a)?'🟡 Inventario pendiente':'🟢 Inventario confirmado'}${a.inventoryConfirmedAt?' · '+new Date(a.inventoryConfirmedAt).toLocaleString():''}</p><div class="archiveGrid"><div class="archiveStat"><small>Total</small><b>${money(g.total)}</b></div><div class="archiveStat"><small>🛵 Uber</small><b>${money(g.uber)}</b></div><div class="archiveStat"><small>🛵 DiDi</small><b>${money(g.didi)}</b></div><div class="archiveStat"><small>🪑 Mesas</small><b>${money(g.mesa)}</b></div><div class="archiveStat"><small>🥡 Para llevar</small><b>${money(g.llevar)}</b></div><div class="archiveStat"><small>👤 Personal</small><b>${money(g.personal)}</b></div><div class="archiveStat"><small>Pedidos</small><b>${g.count}</b></div><div class="archiveStat"><small>Errores</small><b>${g.errors}</b></div></div>${renderProductCounts(a.orders)}${renderErrors(a.orders)}${invSection}${(a.orders||[]).map(o=>archiveOrderCard(a,o)).join('')}</div>`;$('archiveBack').onclick=renderArchiveCards;if($('confirmArchiveInventory'))$('confirmArchiveInventory').onclick=()=>confirmArchiveInventory(a.id);document.querySelectorAll('[data-archive-inv]').forEach(b=>b.onclick=()=>{flash(b);adjustArchiveInventory(Number(b.dataset.archiveInv),b.dataset.invId,Number(b.dataset.delta),Number(b.dataset.base))});document.querySelectorAll('[data-del-archive]').forEach(b=>b.onclick=()=>deleteArchive(Number(b.dataset.delArchive)));document.querySelectorAll('[data-archive-edit]').forEach(b=>b.onclick=()=>{const [aid,oid]=b.dataset.archiveEdit.split('|').map(Number);editOrder(oid,aid)})}
function renderInventory(keepPosition){
const restore=keepPosition||{};
const inv=getInventory(), sold=inventoryUsage(state.orders);
$('screenArchives').innerHTML=`<div class="panel"><div class="row between"><h2>📦 Inventario</h2><div class="row"><button id="resetInventoryZero" class="danger">Reiniciar a 0</button><button id="adminBack">Volver</button></div></div><p class="mut">Inicial y Final pueden ajustarse con botones. Vendido se calcula automáticamente con los pedidos correctos del día.</p><div class="inventoryWrap"><table class="inventoryTable"><thead><tr><th>Producto</th><th>Inicial</th><th>Compra</th><th>Vendido</th><th>Esperado</th><th>Final</th><th>Dif.</th></tr></thead><tbody>${INV_ITEMS.map(([id,name])=>{const r=inv[id]||{initial:0,purchase:0,final:null};const initial=Number(r.initial||0), purchase=Number(r.purchase||0), vendido=Number(sold[id]||0), esperado=initial+purchase-vendido, final=(r.final===null||r.final===undefined)?esperado:Number(r.final||0), diff=final-esperado;return `<tr><td>${name}</td><td><div class="stepper"><button data-inv="${id}" data-field="initial" data-delta="-1">−</button><span>${initial}</span><button data-inv="${id}" data-field="initial" data-delta="1">+</button></div></td><td><div class="stepper"><button data-inv="${id}" data-field="purchase" data-delta="-1">−</button><span>${purchase}</span><button data-inv="${id}" data-field="purchase" data-delta="1">+</button></div></td><td>${vendido}</td><td>${esperado}</td><td><div class="stepper"><button data-inv="${id}" data-field="final" data-delta="-1" data-base="${final}">−</button><span>${final}</span><button data-inv="${id}" data-field="final" data-delta="1" data-base="${final}">+</button></div></td><td class="${diff<0?'diffNeg':diff>0?'diffPos':'diffZero'}">${diff}</td></tr>`}).join('')}</tbody></table></div></div>`;
$('adminBack').onclick=renderAdminHome;
if($('resetInventoryZero'))$('resetInventoryZero').onclick=()=>{
  if(!confirm('Esto pondrá en 0 el inventario actual. No borra pedidos ni cierres. ¿Continuar?'))return;
  zeroInventory();
  localStorage.setItem(INVENTORY_RESET_MARKER,'1');
  renderInventory();
  alert('Inventario actual reiniciado en 0.');
};
if(restore.windowY!==undefined||restore.screenY!==undefined||restore.tableY!==undefined){setTimeout(()=>{if(restore.windowY!==undefined)window.scrollTo(0,restore.windowY);if($('screenArchives')&&restore.screenY!==undefined)$('screenArchives').scrollTop=restore.screenY;const wrap=document.querySelector('#screenArchives .inventoryWrap');if(wrap&&restore.tableY!==undefined)wrap.scrollTop=restore.tableY;},0)}
document.querySelectorAll('[data-inv]').forEach(b=>b.onclick=()=>{flash(b);const currentWrap=document.querySelector('#screenArchives .inventoryWrap');const keep={windowY:window.scrollY,screenY:$('screenArchives')?$('screenArchives').scrollTop:0,tableY:currentWrap?currentWrap.scrollTop:0};const inv=getInventory(), id=b.dataset.inv, f=b.dataset.field, delta=Number(b.dataset.delta);if(!inv[id])inv[id]={initial:0,purchase:0,final:null};let cur=f==='final'?(inv[id].final===null||inv[id].final===undefined?Number(b.dataset.base||0):Number(inv[id].final||0)):Number(inv[id][f]||0);cur=Math.max(0,cur+delta);inv[id][f]=cur;setInventory(inv);renderInventory(keep)})}
function renderTabs(){[['tabNew','screenNew'],['tabActive','screenActive'],['tabClose','screenClose']].forEach(([b,s])=>$(b).onclick=()=>show(s,b));if($('archivesBtn')){$('archivesBtn').textContent='Administración';$('archivesBtn').onclick=()=>{if(ownerPass()){renderAdminHome();show('screenArchives','tabClose')}}}if($('backClose'))$('backClose').onclick=()=>show('screenClose','tabClose')}
function ownerPass(){const p=prompt('Contraseña de administración:');return p===OWNER_PASSWORD}
function closeDay(){if(!state.orders.length){alert('No hay pedidos para cerrar.');return}if(!confirm('Se guardarán ventas y pedidos. El inventario quedará pendiente para que el administrador lo confirme después. ¿Cerrar día?'))return;const now=new Date();const snapshot=buildInventorySnapshot(state.orders,true);const archive={id:Date.now(),closedAt:now.toISOString(),label:now.toLocaleDateString(),orders:JSON.parse(JSON.stringify(state.orders)),inventory:snapshot,inventoryStatus:'pending',summary:buildSummary(state.orders,'Corte guardado',null)};state.archives.unshift(archive);carryInventoryExpectedForward(snapshot);state.orders=[];state.seq=1;save();renderOrders();renderSummary();if($('screenArchives')&&$('screenArchives').classList.contains('on'))renderAdminHome();$('next').textContent='#001';alert('Corte guardado. Ya puedes iniciar el nuevo día desde #001. El inventario quedó pendiente para confirmar en Administración.')}
function renderArchives(){renderArchiveCards()}
$('resetCounter').onclick=()=>{if(confirm('Esto reinicia el número de pedido a #001. No borra pedidos guardados.')){state.seq=1;save();$('next').textContent='#001';renderSummary()}};$('closeDay').onclick=closeDay;runV6InventoryReset();setInterval(renderOrders,60000);init();
})();
